/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package VIEW;

import DATA.UsuarioEsqueceuSenhaData;
import MODEL.UsuarioEsqueceuSenhaModel;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;

/**
 *
 * @author Roberto Junior Akira
 */
public class JFEsqueceuSenha extends javax.swing.JFrame {
    private UsuarioEsqueceuSenhaModel obj;
    private UsuarioEsqueceuSenhaData DAO;

    /**
     * Creates new form JFEsqueceuSenha
     */
    public JFEsqueceuSenha() {
        initComponents();
        obj = new UsuarioEsqueceuSenhaModel();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jpEsqueceuSenha = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        jlEsqueciMinhaSenha = new javax.swing.JLabel();
        ltTexto1 = new javax.swing.JLabel();
        jlTexto2 = new javax.swing.JLabel();
        jlCPF = new javax.swing.JLabel();
        jtfCPF = new javax.swing.JTextField();
        jlDataNascimento = new javax.swing.JLabel();
        jtfDataNascimento = new javax.swing.JTextField();
        jtbVerificar = new javax.swing.JToggleButton();
        jlTexto3 = new javax.swing.JLabel();
        jlNomeMae = new javax.swing.JLabel();
        jtfNomeMae = new javax.swing.JTextField();
        jlSuaSenha = new javax.swing.JLabel();
        jbVoltar = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setResizable(false);

        jpEsqueceuSenha.setBackground(new java.awt.Color(143, 197, 142));

        jlEsqueciMinhaSenha.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        jlEsqueciMinhaSenha.setText("Esqueci minha Senha");

        ltTexto1.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        ltTexto1.setText("Digite o seu CPF, sua data de nascimento");

        jlTexto2.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        jlTexto2.setText("e o nome da sua mãe que foram");

        jlCPF.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        jlCPF.setText("CPF:");

        jtfCPF.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N

        jlDataNascimento.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        jlDataNascimento.setText("Data de nascimento");

        jtfDataNascimento.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N

        jtbVerificar.setBackground(new java.awt.Color(51, 153, 0));
        jtbVerificar.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        jtbVerificar.setText("Verificar");
        jtbVerificar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jtbVerificarActionPerformed(evt);
            }
        });

        jlTexto3.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        jlTexto3.setText("cadastrados!");

        jlNomeMae.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        jlNomeMae.setText("Nome da Mãe");

        jtfNomeMae.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N

        jlSuaSenha.setText("jLabel1");

        jbVoltar.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        jbVoltar.setText("Voltar");
        jbVoltar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbVoltarActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                        .addComponent(jlEsqueciMinhaSenha)
                        .addGap(69, 69, 69))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                        .addComponent(jlTexto2)
                        .addGap(48, 48, 48))))
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(18, 18, 18)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jtfCPF, javax.swing.GroupLayout.PREFERRED_SIZE, 267, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addComponent(jlSuaSenha)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(jbVoltar))
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addComponent(jlDataNascimento)
                                .addGap(0, 163, Short.MAX_VALUE)))
                        .addContainerGap())
                    .addComponent(jlCPF)
                    .addComponent(jtfDataNascimento, javax.swing.GroupLayout.PREFERRED_SIZE, 267, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jlNomeMae)
                    .addComponent(jtfNomeMae, javax.swing.GroupLayout.PREFERRED_SIZE, 267, javax.swing.GroupLayout.PREFERRED_SIZE)))
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(31, 31, 31)
                        .addComponent(ltTexto1))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(111, 111, 111)
                        .addComponent(jlTexto3))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(107, 107, 107)
                        .addComponent(jtbVerificar)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(21, 21, 21)
                .addComponent(jlEsqueciMinhaSenha)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(ltTexto1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jlTexto2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jlTexto3)
                .addGap(18, 18, 18)
                .addComponent(jlCPF)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jtfCPF, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jlDataNascimento)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jtfDataNascimento, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jlNomeMae)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jtfNomeMae, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jtbVerificar)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 19, Short.MAX_VALUE)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jlSuaSenha)
                    .addComponent(jbVoltar))
                .addGap(13, 13, 13))
        );

        javax.swing.GroupLayout jpEsqueceuSenhaLayout = new javax.swing.GroupLayout(jpEsqueceuSenha);
        jpEsqueceuSenha.setLayout(jpEsqueceuSenhaLayout);
        jpEsqueceuSenhaLayout.setHorizontalGroup(
            jpEsqueceuSenhaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jpEsqueceuSenhaLayout.createSequentialGroup()
                .addGap(22, 22, 22)
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(25, Short.MAX_VALUE))
        );
        jpEsqueceuSenhaLayout.setVerticalGroup(
            jpEsqueceuSenhaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jpEsqueceuSenhaLayout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(25, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jpEsqueceuSenha, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jpEsqueceuSenha, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void jtbVerificarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jtbVerificarActionPerformed
        validarCampos();
//        UsuarioEsqueceuSenhaModel DAO;
//        try {
//            DAO = new UsuarioEsqueceuSenhaData();
//            UsuarioEsqueceuSenhaModel obj = DAO.recuperarSenha(jtfCPF.getText(), jtfDataNascimento.getText(), jtfNomeMae.getText());
//            if(obj==null){
//                JOptionPane.showMessageDialog(null, "Não existe usuário com este CPF, este e-mail, ou com o nome da mãe informado. Favor, verifique!");
//            } else {
//                jlSuaSenha.setText("Sua senha é: "+obj.getSenha());
//            }
//        } catch (Exception ex) {
//            Logger.getLogger(JFEsqueceuSenha.class.getName()).log(Level.SEVERE, null, ex);
//        }
    }//GEN-LAST:event_jtbVerificarActionPerformed

    private void jbVoltarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbVoltarActionPerformed
        new JFLogin().setVisible(true); //Abre a janela JFLoguin.
        dispose(); //Fecha a janela JFEsqueceuSenha.// TODO add your handling code here:
    }//GEN-LAST:event_jbVoltarActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(JFEsqueceuSenha.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(JFEsqueceuSenha.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(JFEsqueceuSenha.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(JFEsqueceuSenha.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new JFEsqueceuSenha().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel jPanel2;
    private javax.swing.JButton jbVoltar;
    private javax.swing.JLabel jlCPF;
    private javax.swing.JLabel jlDataNascimento;
    private javax.swing.JLabel jlEsqueciMinhaSenha;
    private javax.swing.JLabel jlNomeMae;
    private javax.swing.JLabel jlSuaSenha;
    private javax.swing.JLabel jlTexto2;
    private javax.swing.JLabel jlTexto3;
    private javax.swing.JPanel jpEsqueceuSenha;
    private javax.swing.JToggleButton jtbVerificar;
    private javax.swing.JTextField jtfCPF;
    private javax.swing.JTextField jtfDataNascimento;
    private javax.swing.JTextField jtfNomeMae;
    private javax.swing.JLabel ltTexto1;
    // End of variables declaration//GEN-END:variables

    private boolean validarCampos(){
        if(jtfCPF.getText().equalsIgnoreCase("")) //Verifica se o campo CPF está em branco.
        {
            JOptionPane.showMessageDialog(this, "O campo CPF está em branco.\nFavor preencher.", "ATENÇÃO", 
                JOptionPane.INFORMATION_MESSAGE);
            jtfCPF.requestFocus(); //Retorna o cursor para o campo CPF.
        }
        else
        {
            if(jtfDataNascimento.getText().equalsIgnoreCase("")) //Verifica se o campo Data de nascimento está em branco.
            {
                JOptionPane.showMessageDialog(this, "O campo Data de Nascimento está em branco.\nFavor preencher.", "ATENÇÃO", 
                        JOptionPane.INFORMATION_MESSAGE);
                jtfDataNascimento.requestFocus(); //Retorna o cursor para o campo Data de Nascimento.
            }
            else
            {
                if(jtfNomeMae.getText().equalsIgnoreCase("")) //Verifica se o campo Nome da mãe está em branco.
                {
                    JOptionPane.showMessageDialog(this, "O campo Nome da mãe está em branco.\nFavor preencher.", "ATENÇÃO", 
                            JOptionPane.INFORMATION_MESSAGE);
                    jtfNomeMae.requestFocus(); //Retorna o cursor para o campo Nome da mãe.
                }
            }
        }
        return false;
    }
}
