/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package VIEW;

import javax.swing.JOptionPane;

/**
 *
 * @author Roberto Junior Akira
 */
public class JFLogin extends javax.swing.JFrame {

    /**
     * Creates new form JFLogin
     */
    public JFLogin() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jpAzul = new javax.swing.JPanel();
        jlCarrinho = new javax.swing.JLabel();
        jlSupermercado = new javax.swing.JLabel();
        jlRiverland = new javax.swing.JLabel();
        jpCinza = new javax.swing.JPanel();
        jlUsuário = new javax.swing.JLabel();
        jtfUsuario = new javax.swing.JTextField();
        jlSenha = new javax.swing.JLabel();
        jpfSenha = new javax.swing.JPasswordField();
        jbEntrar = new javax.swing.JButton();
        jlEsqueceuSenha = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Acesso");
        setResizable(false);

        jpAzul.setBackground(new java.awt.Color(97, 150, 190));
        jpAzul.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        jpAzul.setToolTipText("Acesso ao sistema");

        jlCarrinho.setIcon(new javax.swing.ImageIcon(getClass().getResource("/IMAGENS/carrinho96.png"))); // NOI18N

        jlSupermercado.setFont(new java.awt.Font("Impact", 0, 28)); // NOI18N
        jlSupermercado.setText("SUPERMERCADO");

        jlRiverland.setFont(new java.awt.Font("Impact", 0, 28)); // NOI18N
        jlRiverland.setText("RIVERLAND");

        jpCinza.setBackground(new java.awt.Color(184, 184, 184));
        jpCinza.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 0), 1, true));

        jlUsuário.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        jlUsuário.setText("Usuário:");

        jtfUsuario.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N

        jlSenha.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        jlSenha.setText("Senha:");

        jpfSenha.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N

        jbEntrar.setBackground(new java.awt.Color(12, 175, 53));
        jbEntrar.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        jbEntrar.setText("ENTRAR");
        jbEntrar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbEntrarActionPerformed(evt);
            }
        });

        jlEsqueceuSenha.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        jlEsqueceuSenha.setText("Esqueci minha senha?");
        jlEsqueceuSenha.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jlEsqueceuSenhaMouseClicked(evt);
            }
        });

        javax.swing.GroupLayout jpCinzaLayout = new javax.swing.GroupLayout(jpCinza);
        jpCinza.setLayout(jpCinzaLayout);
        jpCinzaLayout.setHorizontalGroup(
            jpCinzaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jpCinzaLayout.createSequentialGroup()
                .addContainerGap(29, Short.MAX_VALUE)
                .addGroup(jpCinzaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.CENTER)
                    .addComponent(jbEntrar)
                    .addComponent(jlEsqueceuSenha)
                    .addGroup(jpCinzaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                        .addComponent(jlUsuário)
                        .addComponent(jlSenha)
                        .addComponent(jtfUsuario)
                        .addComponent(jpfSenha, javax.swing.GroupLayout.PREFERRED_SIZE, 266, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(25, 25, 25))
        );
        jpCinzaLayout.setVerticalGroup(
            jpCinzaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jpCinzaLayout.createSequentialGroup()
                .addContainerGap(26, Short.MAX_VALUE)
                .addComponent(jlUsuário)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jtfUsuario, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jlSenha)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jpfSenha, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jbEntrar)
                .addGap(18, 18, 18)
                .addComponent(jlEsqueceuSenha)
                .addContainerGap())
        );

        javax.swing.GroupLayout jpAzulLayout = new javax.swing.GroupLayout(jpAzul);
        jpAzul.setLayout(jpAzulLayout);
        jpAzulLayout.setHorizontalGroup(
            jpAzulLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jpAzulLayout.createSequentialGroup()
                .addContainerGap(20, Short.MAX_VALUE)
                .addGroup(jpAzulLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jpCinza, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jpAzulLayout.createSequentialGroup()
                        .addComponent(jlCarrinho)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jpAzulLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.CENTER)
                            .addComponent(jlRiverland)
                            .addComponent(jlSupermercado))
                        .addGap(12, 12, 12)))
                .addGap(25, 25, 25))
        );
        jpAzulLayout.setVerticalGroup(
            jpAzulLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jpAzulLayout.createSequentialGroup()
                .addGroup(jpAzulLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jpAzulLayout.createSequentialGroup()
                        .addContainerGap(22, Short.MAX_VALUE)
                        .addComponent(jlSupermercado)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jlRiverland)
                        .addGap(27, 27, 27))
                    .addGroup(jpAzulLayout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jlCarrinho)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                .addComponent(jpCinza, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(20, 20, 20))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jpAzul, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jpAzul, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void jbEntrarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbEntrarActionPerformed
        if(jtfUsuario.getText().equalsIgnoreCase("Roberto") &&
                jpfSenha.getText().equalsIgnoreCase("2020")) //equalsIgnoreCase verifica
            //os caracteres digitado não importando se estão com letras maiúscula ou minúsculas.
        {
            JOptionPane.showMessageDialog(this, "Bem vindo ao\nSupermercado Riverland!",
                "Acesso ao sistema",JOptionPane.INFORMATION_MESSAGE); //Abre uma janela informando que
            //o sistema foi aberto.
            new JFPrincipal().setVisible(true); //Abre a janela JFPrincipal
            dispose(); //Fecha a janela JFLogin.
        }
        else
            {JOptionPane.showMessageDialog(this, "Usuário ou Senha inválidos!",
                "Meu sistema",JOptionPane.INFORMATION_MESSAGE); //Abre uma janela informando que
            //o usuário ou a senha foram digitados incorretamentes.
                jtfUsuario.setText(""); //Limpa o campo de usuário.
                jpfSenha.setText(null); //Limpa o campo de senha.
                jtfUsuario.requestFocus();} //Volta o cursor para o campo usuário.
    }//GEN-LAST:event_jbEntrarActionPerformed

    private void jlEsqueceuSenhaMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jlEsqueceuSenhaMouseClicked
        new JFEsqueceuSenha().setVisible(true);
        dispose();
    }//GEN-LAST:event_jlEsqueceuSenhaMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(JFLogin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(JFLogin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(JFLogin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(JFLogin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new JFLogin().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jbEntrar;
    private javax.swing.JLabel jlCarrinho;
    private javax.swing.JLabel jlEsqueceuSenha;
    private javax.swing.JLabel jlRiverland;
    private javax.swing.JLabel jlSenha;
    private javax.swing.JLabel jlSupermercado;
    private javax.swing.JLabel jlUsuário;
    private javax.swing.JPanel jpAzul;
    private javax.swing.JPanel jpCinza;
    private javax.swing.JPasswordField jpfSenha;
    private javax.swing.JTextField jtfUsuario;
    // End of variables declaration//GEN-END:variables
}
