/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package VIEW;

import MODEL.UsuarioModel;
import DATA.UsuarioData;
import java.awt.Component;

/**
 *
 * @author Roberto Junior Akira
 */
public class JFPrincipal extends javax.swing.JFrame {

    /**
     * Creates new form JFPrincipal1
     */
    public JFPrincipal() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jbUsuario = new javax.swing.JButton();
        jbLoja = new javax.swing.JButton();
        jbFuncionarios = new javax.swing.JButton();
        jbClientes = new javax.swing.JButton();
        jbFornecedores = new javax.swing.JButton();
        jbSobre = new javax.swing.JButton();
        jbSair = new javax.swing.JButton();
        jdpPrincipal1 = new javax.swing.JDesktopPane();
        jlCarrinho = new javax.swing.JLabel();
        jlSupermercado = new javax.swing.JLabel();
        jlRiverland = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jbUsuario.setFont(new java.awt.Font("Times New Roman", 1, 10)); // NOI18N
        jbUsuario.setIcon(new javax.swing.ImageIcon(getClass().getResource("/IMAGENS/usuario.png"))); // NOI18N
        jbUsuario.setText("USUÁRIO");
        jbUsuario.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        jbUsuario.setMaximumSize(new java.awt.Dimension(81, 73));
        jbUsuario.setMinimumSize(new java.awt.Dimension(81, 73));
        jbUsuario.setPreferredSize(new java.awt.Dimension(81, 73));
        jbUsuario.setVerticalAlignment(javax.swing.SwingConstants.BOTTOM);
        jbUsuario.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        jbUsuario.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbUsuarioActionPerformed(evt);
            }
        });

        jbLoja.setFont(new java.awt.Font("Times New Roman", 1, 10)); // NOI18N
        jbLoja.setIcon(new javax.swing.ImageIcon(getClass().getResource("/IMAGENS/loja.png"))); // NOI18N
        jbLoja.setText("LOJA");
        jbLoja.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        jbLoja.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        jbLoja.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbLojaActionPerformed(evt);
            }
        });

        jbFuncionarios.setFont(new java.awt.Font("Times New Roman", 1, 10)); // NOI18N
        jbFuncionarios.setIcon(new javax.swing.ImageIcon(getClass().getResource("/IMAGENS/funcionario.png"))); // NOI18N
        jbFuncionarios.setText("FUNCIONÁRIOS");
        jbFuncionarios.setToolTipText("");
        jbFuncionarios.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        jbFuncionarios.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        jbFuncionarios.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbFuncionariosActionPerformed(evt);
            }
        });

        jbClientes.setFont(new java.awt.Font("Times New Roman", 1, 10)); // NOI18N
        jbClientes.setIcon(new javax.swing.ImageIcon(getClass().getResource("/IMAGENS/cliente.png"))); // NOI18N
        jbClientes.setText("CLIENTES");
        jbClientes.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        jbClientes.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        jbClientes.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbClientesActionPerformed(evt);
            }
        });

        jbFornecedores.setFont(new java.awt.Font("Times New Roman", 1, 10)); // NOI18N
        jbFornecedores.setIcon(new javax.swing.ImageIcon(getClass().getResource("/IMAGENS/fornec.png"))); // NOI18N
        jbFornecedores.setText("FORNECEDORES");
        jbFornecedores.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        jbFornecedores.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        jbFornecedores.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbFornecedoresActionPerformed(evt);
            }
        });

        jbSobre.setFont(new java.awt.Font("Times New Roman", 1, 10)); // NOI18N
        jbSobre.setIcon(new javax.swing.ImageIcon(getClass().getResource("/IMAGENS/sobre.png"))); // NOI18N
        jbSobre.setText("SOBRE");
        jbSobre.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        jbSobre.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        jbSobre.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbSobreActionPerformed(evt);
            }
        });

        jbSair.setFont(new java.awt.Font("Times New Roman", 1, 10)); // NOI18N
        jbSair.setIcon(new javax.swing.ImageIcon(getClass().getResource("/IMAGENS/power.png"))); // NOI18N
        jbSair.setText("SAIR");
        jbSair.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        jbSair.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        jbSair.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbSairActionPerformed(evt);
            }
        });

        jdpPrincipal1.setBackground(new java.awt.Color(0, 102, 153));
        jdpPrincipal1.setPreferredSize(new java.awt.Dimension(1173, 365));

        jlCarrinho.setIcon(new javax.swing.ImageIcon(getClass().getResource("/IMAGENS/carrinho96.png"))); // NOI18N

        jlSupermercado.setFont(new java.awt.Font("Impact", 0, 28)); // NOI18N
        jlSupermercado.setText("SUPERMERCADO");

        jlRiverland.setFont(new java.awt.Font("Impact", 0, 28)); // NOI18N
        jlRiverland.setText("RIVERLAND");

        jdpPrincipal1.setLayer(jlCarrinho, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jdpPrincipal1.setLayer(jlSupermercado, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jdpPrincipal1.setLayer(jlRiverland, javax.swing.JLayeredPane.DEFAULT_LAYER);

        javax.swing.GroupLayout jdpPrincipal1Layout = new javax.swing.GroupLayout(jdpPrincipal1);
        jdpPrincipal1.setLayout(jdpPrincipal1Layout);
        jdpPrincipal1Layout.setHorizontalGroup(
            jdpPrincipal1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jdpPrincipal1Layout.createSequentialGroup()
                .addGap(492, 492, 492)
                .addComponent(jlCarrinho)
                .addGroup(jdpPrincipal1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jdpPrincipal1Layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jlSupermercado))
                    .addGroup(jdpPrincipal1Layout.createSequentialGroup()
                        .addGap(32, 32, 32)
                        .addComponent(jlRiverland)))
                .addContainerGap(466, Short.MAX_VALUE))
        );
        jdpPrincipal1Layout.setVerticalGroup(
            jdpPrincipal1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jdpPrincipal1Layout.createSequentialGroup()
                .addGap(273, 273, 273)
                .addGroup(jdpPrincipal1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jdpPrincipal1Layout.createSequentialGroup()
                        .addComponent(jlSupermercado)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jlRiverland)
                        .addGap(10, 10, 10))
                    .addComponent(jlCarrinho))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jbLoja, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jbUsuario, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jbClientes, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jbFuncionarios, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(jbFornecedores, javax.swing.GroupLayout.PREFERRED_SIZE, 117, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jbSobre, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jbSair, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jdpPrincipal1, javax.swing.GroupLayout.DEFAULT_SIZE, 1237, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(14, 14, 14)
                .addComponent(jbUsuario, javax.swing.GroupLayout.PREFERRED_SIZE, 83, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jbLoja, javax.swing.GroupLayout.PREFERRED_SIZE, 84, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jbFuncionarios, javax.swing.GroupLayout.PREFERRED_SIZE, 84, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jbClientes, javax.swing.GroupLayout.PREFERRED_SIZE, 84, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jbFornecedores, javax.swing.GroupLayout.PREFERRED_SIZE, 84, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(11, 11, 11)
                .addComponent(jbSobre, javax.swing.GroupLayout.PREFERRED_SIZE, 84, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(11, 11, 11)
                .addComponent(jbSair, javax.swing.GroupLayout.PREFERRED_SIZE, 84, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addComponent(jdpPrincipal1, javax.swing.GroupLayout.DEFAULT_SIZE, 678, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jbUsuarioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbUsuarioActionPerformed
        
        JIFUsuario janela = new JIFUsuario();
        jdpPrincipal1.add(janela);
        janela.setVisible(true);
    }//GEN-LAST:event_jbUsuarioActionPerformed

    private void jbLojaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbLojaActionPerformed
        JIFLoja janela = new JIFLoja();
        jdpPrincipal1.add(janela);
        janela.setVisible(true);
    }//GEN-LAST:event_jbLojaActionPerformed

    private void jbFuncionariosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbFuncionariosActionPerformed
        JIFFuncionarios janela = new JIFFuncionarios();
        jdpPrincipal1.add(janela);
        janela.setVisible(true);
    }//GEN-LAST:event_jbFuncionariosActionPerformed

    private void jbClientesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbClientesActionPerformed
        JIFClientes janela = new JIFClientes();
        jdpPrincipal1.add(janela);
        janela.setVisible(true);
    }//GEN-LAST:event_jbClientesActionPerformed

    private void jbFornecedoresActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbFornecedoresActionPerformed
        JIFFornecedores janela = new JIFFornecedores();
        jdpPrincipal1.add(janela);
        janela.setVisible(true);
    }//GEN-LAST:event_jbFornecedoresActionPerformed

    private void jbSobreActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbSobreActionPerformed
        JIFSobre janela = new JIFSobre();
        jdpPrincipal1.add(janela);
        janela.setVisible(true);
    }//GEN-LAST:event_jbSobreActionPerformed

    private void jbSairActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbSairActionPerformed
        new JFSair().setVisible(true);
    }//GEN-LAST:event_jbSairActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(JFPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(JFPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(JFPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(JFPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new JFPrincipal().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jbClientes;
    private javax.swing.JButton jbFornecedores;
    private javax.swing.JButton jbFuncionarios;
    private javax.swing.JButton jbLoja;
    private javax.swing.JButton jbSair;
    private javax.swing.JButton jbSobre;
    private javax.swing.JButton jbUsuario;
    public static javax.swing.JDesktopPane jdpPrincipal1;
    private javax.swing.JLabel jlCarrinho;
    private javax.swing.JLabel jlRiverland;
    private javax.swing.JLabel jlSupermercado;
    // End of variables declaration//GEN-END:variables
}
