/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package VIEW;

import MODEL.ClientesModel;
import DATA.ClientesData;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
/**
 *
 * @author Roberto Junior Akira
 */
public class JIFClientesFisicos extends javax.swing.JInternalFrame {
    private ClientesModel obj;
    private ClientesData DAO;
    /**
     * Creates new form JIFVisualizarCadClienteFisico
     */
    public JIFClientesFisicos() {
        initComponents();
        obj = new ClientesModel();
        try {
            DAO = new ClientesData();
        } catch (Exception ex) {
            Logger.getLogger(JIFClientesFisicos.class.getName()).log(Level.SEVERE, null, ex);
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        jpCadatroClienteFisico = new javax.swing.JPanel();
        jlCodigoClienteFisico = new javax.swing.JLabel();
        jlCodigoNumClienteFisico = new javax.swing.JLabel();
        jpDadosPessoaisClienteFisico = new javax.swing.JPanel();
        jlNomeClienteFisico = new javax.swing.JLabel();
        jtfnomeClienteFisico = new javax.swing.JTextField();
        jlCpfClienteFisico = new javax.swing.JLabel();
        jtfCpfClienteFisico = new javax.swing.JTextField();
        jpContatoClienteFisico = new javax.swing.JPanel();
        jpEnderecoClienteFisico = new javax.swing.JPanel();
        jlLogadouroClienteFisico = new javax.swing.JLabel();
        jtfLogadouroClienteFisico = new javax.swing.JTextField();
        jlNumeroEndClienteFisico = new javax.swing.JLabel();
        jtfNumeroEndClienteFisico = new javax.swing.JTextField();
        jlComplementoEndClienteFisico = new javax.swing.JLabel();
        jtfComplementoEndClienteFisico = new javax.swing.JTextField();
        jlBairroEndClienteFisico = new javax.swing.JLabel();
        jtfBairroEndClienteFisico = new javax.swing.JTextField();
        jlCepEndClienteFisico = new javax.swing.JLabel();
        jtfCepEndClienteFisico = new javax.swing.JTextField();
        jlCidadeEndClienteFisico = new javax.swing.JLabel();
        jtfCidadeEndClienteFisico = new javax.swing.JTextField();
        jlEstadoEndClienteFisico = new javax.swing.JLabel();
        jtfEstadoEndClienteFisico = new javax.swing.JTextField();
        jpEmailClienteFisico = new javax.swing.JPanel();
        jtfEmailClienteFisico = new javax.swing.JTextField();
        jpTelefoneClienteFisico = new javax.swing.JPanel();
        jtfTelefoneClienteFisico = new javax.swing.JTextField();
        jbSalvarClienteFisico = new javax.swing.JButton();
        jbEditarClienteFisico = new javax.swing.JButton();
        jbExcluirClienteFisico = new javax.swing.JButton();
        jbCancelarClienteFisico = new javax.swing.JButton();
        jbNovoClienteFisico = new javax.swing.JButton();
        jpClientesFisicos = new javax.swing.JPanel();
        jpDadosFuncionarios1 = new javax.swing.JPanel();
        jtfCodigoClienteFisico = new javax.swing.JTextField();
        jScrollPane2 = new javax.swing.JScrollPane();
        jtClientesFisicos = new javax.swing.JTable();

        setClosable(true);
        setIconifiable(true);

        jpCadatroClienteFisico.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Cliente Físico", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Times New Roman", 1, 12))); // NOI18N

        jlCodigoClienteFisico.setFont(new java.awt.Font("Times New Roman", 1, 12)); // NOI18N
        jlCodigoClienteFisico.setText("Código");

        jlCodigoNumClienteFisico.setFont(new java.awt.Font("Times New Roman", 1, 12)); // NOI18N
        jlCodigoNumClienteFisico.setText("0");

        jpDadosPessoaisClienteFisico.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Dados Pessoais", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Times New Roman", 1, 12))); // NOI18N

        jlNomeClienteFisico.setFont(new java.awt.Font("Times New Roman", 1, 12)); // NOI18N
        jlNomeClienteFisico.setText("Nome completo");

        jtfnomeClienteFisico.setFont(new java.awt.Font("Times New Roman", 0, 12)); // NOI18N
        jtfnomeClienteFisico.setEnabled(false);

        jlCpfClienteFisico.setFont(new java.awt.Font("Times New Roman", 1, 12)); // NOI18N
        jlCpfClienteFisico.setText("CPF");

        jtfCpfClienteFisico.setFont(new java.awt.Font("Times New Roman", 0, 12)); // NOI18N
        jtfCpfClienteFisico.setEnabled(false);

        javax.swing.GroupLayout jpDadosPessoaisClienteFisicoLayout = new javax.swing.GroupLayout(jpDadosPessoaisClienteFisico);
        jpDadosPessoaisClienteFisico.setLayout(jpDadosPessoaisClienteFisicoLayout);
        jpDadosPessoaisClienteFisicoLayout.setHorizontalGroup(
            jpDadosPessoaisClienteFisicoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jpDadosPessoaisClienteFisicoLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jpDadosPessoaisClienteFisicoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jlCpfClienteFisico)
                    .addComponent(jtfCpfClienteFisico, javax.swing.GroupLayout.PREFERRED_SIZE, 270, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jlNomeClienteFisico)
                    .addComponent(jtfnomeClienteFisico, javax.swing.GroupLayout.PREFERRED_SIZE, 590, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jpDadosPessoaisClienteFisicoLayout.setVerticalGroup(
            jpDadosPessoaisClienteFisicoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jpDadosPessoaisClienteFisicoLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jlNomeClienteFisico)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jtfnomeClienteFisico, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jlCpfClienteFisico)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jtfCpfClienteFisico, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jpContatoClienteFisico.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Contato", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Times New Roman", 1, 12))); // NOI18N

        jpEnderecoClienteFisico.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Endereço", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Times New Roman", 1, 12))); // NOI18N

        jlLogadouroClienteFisico.setFont(new java.awt.Font("Times New Roman", 1, 12)); // NOI18N
        jlLogadouroClienteFisico.setText("Logadouro");

        jtfLogadouroClienteFisico.setFont(new java.awt.Font("Times New Roman", 0, 12)); // NOI18N
        jtfLogadouroClienteFisico.setEnabled(false);

        jlNumeroEndClienteFisico.setFont(new java.awt.Font("Times New Roman", 1, 12)); // NOI18N
        jlNumeroEndClienteFisico.setText("Número");

        jtfNumeroEndClienteFisico.setFont(new java.awt.Font("Times New Roman", 0, 12)); // NOI18N
        jtfNumeroEndClienteFisico.setEnabled(false);

        jlComplementoEndClienteFisico.setFont(new java.awt.Font("Times New Roman", 1, 12)); // NOI18N
        jlComplementoEndClienteFisico.setText("Complemento");

        jtfComplementoEndClienteFisico.setFont(new java.awt.Font("Times New Roman", 0, 12)); // NOI18N
        jtfComplementoEndClienteFisico.setEnabled(false);

        jlBairroEndClienteFisico.setFont(new java.awt.Font("Times New Roman", 1, 12)); // NOI18N
        jlBairroEndClienteFisico.setText("Bairro");

        jtfBairroEndClienteFisico.setFont(new java.awt.Font("Times New Roman", 0, 12)); // NOI18N
        jtfBairroEndClienteFisico.setEnabled(false);

        jlCepEndClienteFisico.setFont(new java.awt.Font("Times New Roman", 1, 12)); // NOI18N
        jlCepEndClienteFisico.setText("CEP");

        jtfCepEndClienteFisico.setFont(new java.awt.Font("Times New Roman", 0, 12)); // NOI18N
        jtfCepEndClienteFisico.setEnabled(false);

        jlCidadeEndClienteFisico.setFont(new java.awt.Font("Times New Roman", 1, 12)); // NOI18N
        jlCidadeEndClienteFisico.setText("Cidade");

        jtfCidadeEndClienteFisico.setFont(new java.awt.Font("Times New Roman", 0, 12)); // NOI18N
        jtfCidadeEndClienteFisico.setEnabled(false);

        jlEstadoEndClienteFisico.setFont(new java.awt.Font("Times New Roman", 1, 12)); // NOI18N
        jlEstadoEndClienteFisico.setText("Estado");

        jtfEstadoEndClienteFisico.setFont(new java.awt.Font("Times New Roman", 0, 12)); // NOI18N
        jtfEstadoEndClienteFisico.setEnabled(false);

        javax.swing.GroupLayout jpEnderecoClienteFisicoLayout = new javax.swing.GroupLayout(jpEnderecoClienteFisico);
        jpEnderecoClienteFisico.setLayout(jpEnderecoClienteFisicoLayout);
        jpEnderecoClienteFisicoLayout.setHorizontalGroup(
            jpEnderecoClienteFisicoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jpEnderecoClienteFisicoLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jpEnderecoClienteFisicoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jpEnderecoClienteFisicoLayout.createSequentialGroup()
                        .addGroup(jpEnderecoClienteFisicoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jlBairroEndClienteFisico, javax.swing.GroupLayout.PREFERRED_SIZE, 79, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jtfBairroEndClienteFisico, javax.swing.GroupLayout.PREFERRED_SIZE, 166, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(jpEnderecoClienteFisicoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jlCepEndClienteFisico, javax.swing.GroupLayout.PREFERRED_SIZE, 79, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jtfCepEndClienteFisico, javax.swing.GroupLayout.PREFERRED_SIZE, 128, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(jpEnderecoClienteFisicoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jlCidadeEndClienteFisico, javax.swing.GroupLayout.PREFERRED_SIZE, 79, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jtfCidadeEndClienteFisico, javax.swing.GroupLayout.PREFERRED_SIZE, 136, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(jpEnderecoClienteFisicoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jlEstadoEndClienteFisico, javax.swing.GroupLayout.PREFERRED_SIZE, 79, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jtfEstadoEndClienteFisico, javax.swing.GroupLayout.PREFERRED_SIZE, 107, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(jpEnderecoClienteFisicoLayout.createSequentialGroup()
                        .addGroup(jpEnderecoClienteFisicoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jpEnderecoClienteFisicoLayout.createSequentialGroup()
                                .addComponent(jlLogadouroClienteFisico, javax.swing.GroupLayout.PREFERRED_SIZE, 79, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(0, 0, Short.MAX_VALUE))
                            .addComponent(jtfLogadouroClienteFisico))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(jpEnderecoClienteFisicoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jlNumeroEndClienteFisico, javax.swing.GroupLayout.PREFERRED_SIZE, 79, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jtfNumeroEndClienteFisico, javax.swing.GroupLayout.PREFERRED_SIZE, 107, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(jpEnderecoClienteFisicoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jlComplementoEndClienteFisico, javax.swing.GroupLayout.PREFERRED_SIZE, 79, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jtfComplementoEndClienteFisico, javax.swing.GroupLayout.PREFERRED_SIZE, 107, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addContainerGap())
        );
        jpEnderecoClienteFisicoLayout.setVerticalGroup(
            jpEnderecoClienteFisicoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jpEnderecoClienteFisicoLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jpEnderecoClienteFisicoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jpEnderecoClienteFisicoLayout.createSequentialGroup()
                        .addComponent(jlLogadouroClienteFisico)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jtfLogadouroClienteFisico, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jpEnderecoClienteFisicoLayout.createSequentialGroup()
                        .addComponent(jlNumeroEndClienteFisico)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jtfNumeroEndClienteFisico, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jpEnderecoClienteFisicoLayout.createSequentialGroup()
                        .addComponent(jlComplementoEndClienteFisico)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jtfComplementoEndClienteFisico, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jpEnderecoClienteFisicoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jpEnderecoClienteFisicoLayout.createSequentialGroup()
                        .addComponent(jlBairroEndClienteFisico)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jtfBairroEndClienteFisico, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jpEnderecoClienteFisicoLayout.createSequentialGroup()
                        .addComponent(jlCepEndClienteFisico)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jtfCepEndClienteFisico, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jpEnderecoClienteFisicoLayout.createSequentialGroup()
                        .addComponent(jlCidadeEndClienteFisico)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jtfCidadeEndClienteFisico, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jpEnderecoClienteFisicoLayout.createSequentialGroup()
                        .addComponent(jlEstadoEndClienteFisico)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jtfEstadoEndClienteFisico, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jpEmailClienteFisico.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "E-mail", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Times New Roman", 1, 12))); // NOI18N

        jtfEmailClienteFisico.setFont(new java.awt.Font("Times New Roman", 0, 12)); // NOI18N
        jtfEmailClienteFisico.setEnabled(false);

        javax.swing.GroupLayout jpEmailClienteFisicoLayout = new javax.swing.GroupLayout(jpEmailClienteFisico);
        jpEmailClienteFisico.setLayout(jpEmailClienteFisicoLayout);
        jpEmailClienteFisicoLayout.setHorizontalGroup(
            jpEmailClienteFisicoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jpEmailClienteFisicoLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jtfEmailClienteFisico)
                .addContainerGap())
        );
        jpEmailClienteFisicoLayout.setVerticalGroup(
            jpEmailClienteFisicoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jtfEmailClienteFisico, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        jpTelefoneClienteFisico.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Telefone", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Times New Roman", 1, 12))); // NOI18N

        jtfTelefoneClienteFisico.setFont(new java.awt.Font("Times New Roman", 0, 12)); // NOI18N
        jtfTelefoneClienteFisico.setEnabled(false);

        javax.swing.GroupLayout jpTelefoneClienteFisicoLayout = new javax.swing.GroupLayout(jpTelefoneClienteFisico);
        jpTelefoneClienteFisico.setLayout(jpTelefoneClienteFisicoLayout);
        jpTelefoneClienteFisicoLayout.setHorizontalGroup(
            jpTelefoneClienteFisicoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jpTelefoneClienteFisicoLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jtfTelefoneClienteFisico, javax.swing.GroupLayout.DEFAULT_SIZE, 261, Short.MAX_VALUE)
                .addContainerGap())
        );
        jpTelefoneClienteFisicoLayout.setVerticalGroup(
            jpTelefoneClienteFisicoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jtfTelefoneClienteFisico, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        javax.swing.GroupLayout jpContatoClienteFisicoLayout = new javax.swing.GroupLayout(jpContatoClienteFisico);
        jpContatoClienteFisico.setLayout(jpContatoClienteFisicoLayout);
        jpContatoClienteFisicoLayout.setHorizontalGroup(
            jpContatoClienteFisicoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jpContatoClienteFisicoLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jpContatoClienteFisicoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jpEnderecoClienteFisico, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(jpContatoClienteFisicoLayout.createSequentialGroup()
                        .addComponent(jpEmailClienteFisico, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jpTelefoneClienteFisico, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap())
        );
        jpContatoClienteFisicoLayout.setVerticalGroup(
            jpContatoClienteFisicoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jpContatoClienteFisicoLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jpEnderecoClienteFisico, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jpContatoClienteFisicoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jpEmailClienteFisico, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jpTelefoneClienteFisico, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jbSalvarClienteFisico.setFont(new java.awt.Font("Times New Roman", 1, 12)); // NOI18N
        jbSalvarClienteFisico.setIcon(new javax.swing.ImageIcon(getClass().getResource("/IMAGENS/1salvar.png"))); // NOI18N
        jbSalvarClienteFisico.setText("  Salvar");
        jbSalvarClienteFisico.setEnabled(false);
        jbSalvarClienteFisico.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbSalvarClienteFisicoActionPerformed(evt);
            }
        });

        jbEditarClienteFisico.setFont(new java.awt.Font("Times New Roman", 1, 12)); // NOI18N
        jbEditarClienteFisico.setIcon(new javax.swing.ImageIcon(getClass().getResource("/IMAGENS/1editar.png"))); // NOI18N
        jbEditarClienteFisico.setText("  Editar");
        jbEditarClienteFisico.setEnabled(false);
        jbEditarClienteFisico.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbEditarClienteFisicoActionPerformed(evt);
            }
        });

        jbExcluirClienteFisico.setFont(new java.awt.Font("Times New Roman", 1, 12)); // NOI18N
        jbExcluirClienteFisico.setIcon(new javax.swing.ImageIcon(getClass().getResource("/IMAGENS/1apagar.png"))); // NOI18N
        jbExcluirClienteFisico.setText("  Excluir");
        jbExcluirClienteFisico.setEnabled(false);
        jbExcluirClienteFisico.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbExcluirClienteFisicoActionPerformed(evt);
            }
        });

        jbCancelarClienteFisico.setFont(new java.awt.Font("Times New Roman", 1, 12)); // NOI18N
        jbCancelarClienteFisico.setIcon(new javax.swing.ImageIcon(getClass().getResource("/IMAGENS/1excluir.png"))); // NOI18N
        jbCancelarClienteFisico.setText("  Cancelar");
        jbCancelarClienteFisico.setEnabled(false);
        jbCancelarClienteFisico.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbCancelarClienteFisicoActionPerformed(evt);
            }
        });

        jbNovoClienteFisico.setFont(new java.awt.Font("Times New Roman", 1, 12)); // NOI18N
        jbNovoClienteFisico.setIcon(new javax.swing.ImageIcon(getClass().getResource("/IMAGENS/1novo.png"))); // NOI18N
        jbNovoClienteFisico.setText("  Novo");
        jbNovoClienteFisico.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbNovoClienteFisicoActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jpCadatroClienteFisicoLayout = new javax.swing.GroupLayout(jpCadatroClienteFisico);
        jpCadatroClienteFisico.setLayout(jpCadatroClienteFisicoLayout);
        jpCadatroClienteFisicoLayout.setHorizontalGroup(
            jpCadatroClienteFisicoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jpCadatroClienteFisicoLayout.createSequentialGroup()
                .addGroup(jpCadatroClienteFisicoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jpCadatroClienteFisicoLayout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jlCodigoClienteFisico)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jlCodigoNumClienteFisico))
                    .addGroup(jpCadatroClienteFisicoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                        .addComponent(jpContatoClienteFisico, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jpDadosPessoaisClienteFisico, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jpCadatroClienteFisicoLayout.createSequentialGroup()
                            .addGap(2, 2, 2)
                            .addComponent(jbNovoClienteFisico, javax.swing.GroupLayout.PREFERRED_SIZE, 115, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                            .addComponent(jbEditarClienteFisico, javax.swing.GroupLayout.PREFERRED_SIZE, 123, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                            .addComponent(jbSalvarClienteFisico, javax.swing.GroupLayout.PREFERRED_SIZE, 123, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                            .addComponent(jbCancelarClienteFisico)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                            .addComponent(jbExcluirClienteFisico, javax.swing.GroupLayout.PREFERRED_SIZE, 123, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addGap(0, 0, Short.MAX_VALUE))
        );
        jpCadatroClienteFisicoLayout.setVerticalGroup(
            jpCadatroClienteFisicoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jpCadatroClienteFisicoLayout.createSequentialGroup()
                .addGap(7, 7, 7)
                .addGroup(jpCadatroClienteFisicoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jlCodigoClienteFisico)
                    .addComponent(jlCodigoNumClienteFisico))
                .addGap(18, 18, 18)
                .addComponent(jpDadosPessoaisClienteFisico, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jpContatoClienteFisico, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jpCadatroClienteFisicoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jbEditarClienteFisico)
                    .addComponent(jbSalvarClienteFisico)
                    .addComponent(jbExcluirClienteFisico)
                    .addComponent(jbCancelarClienteFisico)
                    .addComponent(jbNovoClienteFisico))
                .addContainerGap(16, Short.MAX_VALUE))
        );

        jScrollPane1.setViewportView(jpCadatroClienteFisico);

        jpClientesFisicos.setFont(new java.awt.Font("Times New Roman", 0, 12)); // NOI18N

        jpDadosFuncionarios1.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Pesquisar", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Times New Roman", 1, 12))); // NOI18N

        jtfCodigoClienteFisico.setFont(new java.awt.Font("Times New Roman", 0, 12)); // NOI18N

        javax.swing.GroupLayout jpDadosFuncionarios1Layout = new javax.swing.GroupLayout(jpDadosFuncionarios1);
        jpDadosFuncionarios1.setLayout(jpDadosFuncionarios1Layout);
        jpDadosFuncionarios1Layout.setHorizontalGroup(
            jpDadosFuncionarios1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jpDadosFuncionarios1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jtfCodigoClienteFisico, javax.swing.GroupLayout.DEFAULT_SIZE, 441, Short.MAX_VALUE)
                .addContainerGap())
        );
        jpDadosFuncionarios1Layout.setVerticalGroup(
            jpDadosFuncionarios1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jpDadosFuncionarios1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jtfCodigoClienteFisico, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jtClientesFisicos.setFont(new java.awt.Font("Times New Roman", 0, 12)); // NOI18N
        jtClientesFisicos.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null}
            },
            new String [] {
                "CÓDIGO", "NOME", "CPF"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.String.class, java.lang.String.class, java.lang.String.class
            };
            boolean[] canEdit = new boolean [] {
                false, false, false
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jtClientesFisicos.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jtClientesFisicosMouseClicked(evt);
            }
        });
        jScrollPane2.setViewportView(jtClientesFisicos);

        javax.swing.GroupLayout jpClientesFisicosLayout = new javax.swing.GroupLayout(jpClientesFisicos);
        jpClientesFisicos.setLayout(jpClientesFisicosLayout);
        jpClientesFisicosLayout.setHorizontalGroup(
            jpClientesFisicosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jpDadosFuncionarios1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
            .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 477, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        jpClientesFisicosLayout.setVerticalGroup(
            jpClientesFisicosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jpClientesFisicosLayout.createSequentialGroup()
                .addComponent(jpDadosFuncionarios1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 445, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(236, 236, 236))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jpClientesFisicos, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jpClientesFisicos, javax.swing.GroupLayout.PREFERRED_SIZE, 531, Short.MAX_VALUE)
            .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jbEditarClienteFisicoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbEditarClienteFisicoActionPerformed
        jtfnomeClienteFisico.setEnabled(true);
        jtfCpfClienteFisico.setEnabled(true);
        jtfLogadouroClienteFisico.setEnabled(true);
        jtfNumeroEndClienteFisico.setEnabled(true);
        jtfComplementoEndClienteFisico.setEnabled(true);
        jtfBairroEndClienteFisico.setEnabled(true);
        jtfCepEndClienteFisico.setEnabled(true);
        jtfCidadeEndClienteFisico.setEnabled(true);
        jtfEstadoEndClienteFisico.setEnabled(true);
        jtfEmailClienteFisico.setEnabled(true);
        jtfTelefoneClienteFisico.setEnabled(true);
        jbEditarClienteFisico.setEnabled(false);
        jbSalvarClienteFisico.setEnabled(true);
        jbCancelarClienteFisico.setEnabled(true);
        jbExcluirClienteFisico.setEnabled(false);
    }//GEN-LAST:event_jbEditarClienteFisicoActionPerformed

    private void jbSalvarClienteFisicoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbSalvarClienteFisicoActionPerformed
        try {
            if(preencherObjeto()){
                if(DAO.incluirCliFiscico(obj)){
                    if(DAO.incluirEnderecoCliFiscico(obj)){
                        if(DAO.incluirTelefoneCliFiscico(obj)){
                            JOptionPane.showMessageDialog(this, "Produto registrado!",
                                    "Meu sistema", JOptionPane.INFORMATION_MESSAGE);
                            //Salva no banco de dados.
                        }
                    }
                }
            }
        } catch (Exception erro) {
            JOptionPane.showMessageDialog(this, "Erro ao salvar:"+erro.getMessage(),"Sistema", JOptionPane.ERROR_MESSAGE);
        }
    }//GEN-LAST:event_jbSalvarClienteFisicoActionPerformed

    private void jbCancelarClienteFisicoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbCancelarClienteFisicoActionPerformed
        jtfnomeClienteFisico.setEnabled(false);
        jtfCpfClienteFisico.setEnabled(false);
        jtfLogadouroClienteFisico.setEnabled(false);
        jtfNumeroEndClienteFisico.setEnabled(false);
        jtfComplementoEndClienteFisico.setEnabled(false);
        jtfBairroEndClienteFisico.setEnabled(false);
        jtfCepEndClienteFisico.setEnabled(false);
        jtfCidadeEndClienteFisico.setEnabled(false);
        jtfEstadoEndClienteFisico.setEnabled(false);
        jtfEmailClienteFisico.setEnabled(false);
        jtfTelefoneClienteFisico.setEnabled(false);
        jbNovoClienteFisico.setEnabled(true);
        jbEditarClienteFisico.setEnabled(false);
        jbSalvarClienteFisico.setEnabled(false);
        jbCancelarClienteFisico.setEnabled(false);
        jbExcluirClienteFisico.setEnabled(false);
    }//GEN-LAST:event_jbCancelarClienteFisicoActionPerformed

    private void jbExcluirClienteFisicoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbExcluirClienteFisicoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jbExcluirClienteFisicoActionPerformed

    private void jbNovoClienteFisicoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbNovoClienteFisicoActionPerformed
        jtfnomeClienteFisico.setEnabled(true);
        jtfCpfClienteFisico.setEnabled(true);
        jtfLogadouroClienteFisico.setEnabled(true);
        jtfNumeroEndClienteFisico.setEnabled(true);
        jtfComplementoEndClienteFisico.setEnabled(true);
        jtfBairroEndClienteFisico.setEnabled(true);
        jtfCepEndClienteFisico.setEnabled(true);
        jtfCidadeEndClienteFisico.setEnabled(true);
        jtfEstadoEndClienteFisico.setEnabled(true);
        jtfEmailClienteFisico.setEnabled(true);
        jtfTelefoneClienteFisico.setEnabled(true);
        jbEditarClienteFisico.setEnabled(false);
        jbSalvarClienteFisico.setEnabled(true);
        jbCancelarClienteFisico.setEnabled(true);
        jbExcluirClienteFisico.setEnabled(false);
    }//GEN-LAST:event_jbNovoClienteFisicoActionPerformed

    private void jtClientesFisicosMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jtClientesFisicosMouseClicked
        //jbVisualizarClienteFisico.setEnabled(true);
    }//GEN-LAST:event_jtClientesFisicosMouseClicked


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JButton jbCancelarClienteFisico;
    private javax.swing.JButton jbEditarClienteFisico;
    private javax.swing.JButton jbExcluirClienteFisico;
    private javax.swing.JButton jbNovoClienteFisico;
    private javax.swing.JButton jbSalvarClienteFisico;
    private javax.swing.JLabel jlBairroEndClienteFisico;
    private javax.swing.JLabel jlCepEndClienteFisico;
    private javax.swing.JLabel jlCidadeEndClienteFisico;
    private javax.swing.JLabel jlCodigoClienteFisico;
    private javax.swing.JLabel jlCodigoNumClienteFisico;
    private javax.swing.JLabel jlComplementoEndClienteFisico;
    private javax.swing.JLabel jlCpfClienteFisico;
    private javax.swing.JLabel jlEstadoEndClienteFisico;
    private javax.swing.JLabel jlLogadouroClienteFisico;
    private javax.swing.JLabel jlNomeClienteFisico;
    private javax.swing.JLabel jlNumeroEndClienteFisico;
    private javax.swing.JPanel jpCadatroClienteFisico;
    private javax.swing.JPanel jpClientesFisicos;
    private javax.swing.JPanel jpContatoClienteFisico;
    private javax.swing.JPanel jpDadosFuncionarios1;
    private javax.swing.JPanel jpDadosPessoaisClienteFisico;
    private javax.swing.JPanel jpEmailClienteFisico;
    private javax.swing.JPanel jpEnderecoClienteFisico;
    private javax.swing.JPanel jpTelefoneClienteFisico;
    private javax.swing.JTable jtClientesFisicos;
    private javax.swing.JTextField jtfBairroEndClienteFisico;
    private javax.swing.JTextField jtfCepEndClienteFisico;
    private javax.swing.JTextField jtfCidadeEndClienteFisico;
    private javax.swing.JTextField jtfCodigoClienteFisico;
    private javax.swing.JTextField jtfComplementoEndClienteFisico;
    private javax.swing.JTextField jtfCpfClienteFisico;
    private javax.swing.JTextField jtfEmailClienteFisico;
    private javax.swing.JTextField jtfEstadoEndClienteFisico;
    private javax.swing.JTextField jtfLogadouroClienteFisico;
    private javax.swing.JTextField jtfNumeroEndClienteFisico;
    private javax.swing.JTextField jtfTelefoneClienteFisico;
    private javax.swing.JTextField jtfnomeClienteFisico;
    // End of variables declaration//GEN-END:variables

private void limparCampos(){
    jtfnomeClienteFisico.setText("");
    jtfCpfClienteFisico.setText("");
    jtfLogadouroClienteFisico.setText("");
    jtfNumeroEndClienteFisico.setText("");
    jtfComplementoEndClienteFisico.setText("");
    jtfBairroEndClienteFisico.setText("");
    jtfCepEndClienteFisico.setText("");
    jtfCidadeEndClienteFisico.setText("");
    jtfEstadoEndClienteFisico.setText("");
    jtfEmailClienteFisico.setText("");
    jtfTelefoneClienteFisico.setText("");
}

private boolean validarCampos(){
    String msg="";
    if (jtfnomeClienteFisico.getText().length()<3 || jtfnomeClienteFisico.getText().length()>100)
        msg+="\nO campo Nome precisa possuir entre 3 a 100 caracteres!";
    if (!jtfCpfClienteFisico.getText().contains(".") & !jtfCpfClienteFisico.getText().contains("/"))
        msg+="\nO campo CPF falta por '/' ou '.'";
    if (jtfLogadouroClienteFisico.getText().length()<3 || jtfLogadouroClienteFisico.getText().length()>100)
        msg+="\nO campo Logadouro deve conter entre 3 e 100 caracteres!";
    if (jtfNumeroEndClienteFisico.getText().length()<1)
        msg+="\nO campo Número deve conter entre ao menos 1 caracterer!";
    if (jtfComplementoEndClienteFisico.getText().length()<1 || jtfComplementoEndClienteFisico.getText().length()>100)
        msg+="\nO campo Comlemento deve conter 1 e 100 caracteres!";
    if (jtfBairroEndClienteFisico.getText().length()<1 || jtfBairroEndClienteFisico.getText().length()>100)
        msg+="\nO campo Bairro deve conter 1 e 100 caraceres!";
    if (jtfCepEndClienteFisico.getText().length()<1)
        msg+="\nO campo CEP deve conter ao menos 1 caracerer!";
    if (jtfCidadeEndClienteFisico.getText().length()<1 || jtfCidadeEndClienteFisico.getText().length()>100)
        msg+="\nO campo Bairro deve conter 1 e 100 caraceres!";
    if (jtfEstadoEndClienteFisico.getText().length()<1 || jtfEstadoEndClienteFisico.getText().length()>100)
        msg+="\nO campo Bairro deve conter 1 e 100 caraceres!";
    if (!jtfEmailClienteFisico.getText().contains("@") & !jtfEmailClienteFisico.getText().contains("."))
        msg+="\nO campo CPF falta por '@' ou '.'";
    if (jtfTelefoneClienteFisico.getText().length()<11)
        msg+="\nO campo Bairro deve conter no mínimo 11 caraceres!";
    if (msg.isEmpty()) return true;
    else JOptionPane.showMessageDialog(this, "Os campos abaixo precisam de atenção:"
            +msg, "Atenção", JOptionPane.ERROR_MESSAGE);
    return false;
}

private boolean preencherObjeto() throws Exception{
    obj.setNome(jtfnomeClienteFisico.getText());
    obj.setCpf(jtfCpfClienteFisico.getText());
    obj.setLogadouro(jtfLogadouroClienteFisico.getText());
    obj.setNumero(jtfNumeroEndClienteFisico.getText());
    obj.setComplemento(jtfComplementoEndClienteFisico.getText());
    obj.setBairro(jtfBairroEndClienteFisico.getText());
    obj.setCep(Integer.parseInt(jtfCepEndClienteFisico.getText()));
    obj.setCidade(jtfCidadeEndClienteFisico.getText());
    obj.setEstado(jtfEstadoEndClienteFisico.getText());
    obj.setEmail(jtfEmailClienteFisico.getText());
    obj.setTelefone(Integer.parseInt(jtfTelefoneClienteFisico.getText()));
    return true;
}
}
