/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package VIEW;

/**
 *
 * @author Roberto Junior Akira
 */
public class JIFFuncionarios extends javax.swing.JInternalFrame {

    /**
     * Creates new form JIFVisualizarCadatroFuncionario
     */
    public JIFFuncionarios() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        jPanel9 = new javax.swing.JPanel();
        jlCodigoFuncionário = new javax.swing.JLabel();
        jlCodigoNumFuncionario = new javax.swing.JLabel();
        jpDadosPessoaisFuncionario = new javax.swing.JPanel();
        jlNomeFuncionario = new javax.swing.JLabel();
        jtfnomeFuncionario = new javax.swing.JTextField();
        jlSexoFuncionario = new javax.swing.JLabel();
        jcbSexoFuncionario = new javax.swing.JComboBox<>();
        jlCpfFuncionario = new javax.swing.JLabel();
        jtfCpfFuncionario = new javax.swing.JTextField();
        jlRgFuncionario = new javax.swing.JLabel();
        jtfRgFuncionario = new javax.swing.JTextField();
        jlPisNitFuncionario = new javax.swing.JLabel();
        jtfPisNitFuncionario = new javax.swing.JTextField();
        jlDataNascimentoFuncionario = new javax.swing.JLabel();
        jtfDataNascimentoFuncionario = new javax.swing.JTextField();
        jlMaeFuncionario = new javax.swing.JLabel();
        jtfMaeFuncionario = new javax.swing.JTextField();
        jlPaiFuncionario = new javax.swing.JLabel();
        jtfPaiFuncionario = new javax.swing.JTextField();
        jpContatoFuncionario = new javax.swing.JPanel();
        jpEnderecoFuncionario = new javax.swing.JPanel();
        jlLogadouroFuncionario = new javax.swing.JLabel();
        jtfLogadouroFuncionario = new javax.swing.JTextField();
        jlNumeroEndFuncionario = new javax.swing.JLabel();
        jtfNumeroEndFuncionario = new javax.swing.JTextField();
        jlComplementoEndFuncionario = new javax.swing.JLabel();
        jtfComplementoEndFuncionario = new javax.swing.JTextField();
        jlBairroEndFuncionario = new javax.swing.JLabel();
        jtfBairroEndFuncionario = new javax.swing.JTextField();
        jlCepEndFuncionario = new javax.swing.JLabel();
        jtfCepEndFuncionario = new javax.swing.JTextField();
        jlCidadeEndFuncionario = new javax.swing.JLabel();
        jtfCidadeEndFuncionario = new javax.swing.JTextField();
        jlEstadoEndFuncionario = new javax.swing.JLabel();
        jtfEstadoEndFuncionario = new javax.swing.JTextField();
        jpEmailFuncionario = new javax.swing.JPanel();
        jtfEmailFuncionario = new javax.swing.JTextField();
        jpTelefoneFuncionario = new javax.swing.JPanel();
        jtfTelefoneFuncionario = new javax.swing.JTextField();
        jpVinculoFuncionario = new javax.swing.JPanel();
        jtfDataInicioContratoFuncionario = new javax.swing.JTextField();
        jlDataInicioContratoFuncionario = new javax.swing.JLabel();
        jlDataFimContratoFuncionario = new javax.swing.JLabel();
        jtfDataFimContratoFuncionario = new javax.swing.JTextField();
        jlSalarioFuncionario = new javax.swing.JLabel();
        jtfSalarioFuncionario = new javax.swing.JTextField();
        jlCargoFuncionario = new javax.swing.JLabel();
        jtfCargoFuncionario = new javax.swing.JTextField();
        jpSistemaFuncionario = new javax.swing.JPanel();
        jlLoginFuncionario = new javax.swing.JLabel();
        jtfLoginFuncionario = new javax.swing.JTextField();
        jlSenhaFuncionario = new javax.swing.JLabel();
        jtfSenhaFuncionario = new javax.swing.JTextField();
        jbEditarFuncionario = new javax.swing.JButton();
        jbSalvarFuncionario = new javax.swing.JButton();
        jbCancelarFuncionario1 = new javax.swing.JButton();
        jbExcluirFuncionario = new javax.swing.JButton();
        jpFuncionarios = new javax.swing.JPanel();
        jScrollPane2 = new javax.swing.JScrollPane();
        jtFuncionarios = new javax.swing.JTable();
        jpDadosFuncionarios = new javax.swing.JPanel();
        jtfCodigoFunconario = new javax.swing.JTextField();
        jbNovoFuncionario = new javax.swing.JButton();

        setClosable(true);
        setIconifiable(true);

        jPanel9.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Funcionário", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Times New Roman", 1, 12))); // NOI18N

        jlCodigoFuncionário.setFont(new java.awt.Font("Times New Roman", 1, 12)); // NOI18N
        jlCodigoFuncionário.setText("Código");

        jlCodigoNumFuncionario.setFont(new java.awt.Font("Times New Roman", 1, 12)); // NOI18N
        jlCodigoNumFuncionario.setText("0");

        jpDadosPessoaisFuncionario.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Dados Pessoais", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Times New Roman", 1, 12))); // NOI18N

        jlNomeFuncionario.setFont(new java.awt.Font("Times New Roman", 1, 12)); // NOI18N
        jlNomeFuncionario.setText("Nome completo");

        jtfnomeFuncionario.setFont(new java.awt.Font("Times New Roman", 0, 12)); // NOI18N
        jtfnomeFuncionario.setEnabled(false);

        jlSexoFuncionario.setFont(new java.awt.Font("Times New Roman", 1, 12)); // NOI18N
        jlSexoFuncionario.setText("Sexo");

        jcbSexoFuncionario.setFont(new java.awt.Font("Times New Roman", 0, 12)); // NOI18N
        jcbSexoFuncionario.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Selecione", "Masculino", "Feminino", "Outros" }));
        jcbSexoFuncionario.setEnabled(false);

        jlCpfFuncionario.setFont(new java.awt.Font("Times New Roman", 1, 12)); // NOI18N
        jlCpfFuncionario.setText("CPF");

        jtfCpfFuncionario.setFont(new java.awt.Font("Times New Roman", 0, 12)); // NOI18N
        jtfCpfFuncionario.setEnabled(false);

        jlRgFuncionario.setFont(new java.awt.Font("Times New Roman", 1, 12)); // NOI18N
        jlRgFuncionario.setText("RG");

        jtfRgFuncionario.setFont(new java.awt.Font("Times New Roman", 0, 12)); // NOI18N
        jtfRgFuncionario.setEnabled(false);

        jlPisNitFuncionario.setFont(new java.awt.Font("Times New Roman", 1, 12)); // NOI18N
        jlPisNitFuncionario.setText("PIS\\NIT");

        jtfPisNitFuncionario.setFont(new java.awt.Font("Times New Roman", 0, 12)); // NOI18N
        jtfPisNitFuncionario.setEnabled(false);

        jlDataNascimentoFuncionario.setFont(new java.awt.Font("Times New Roman", 1, 12)); // NOI18N
        jlDataNascimentoFuncionario.setText("Data Nascimento");

        jtfDataNascimentoFuncionario.setFont(new java.awt.Font("Times New Roman", 0, 12)); // NOI18N
        jtfDataNascimentoFuncionario.setEnabled(false);

        jlMaeFuncionario.setFont(new java.awt.Font("Times New Roman", 1, 12)); // NOI18N
        jlMaeFuncionario.setText("Mãe");

        jtfMaeFuncionario.setFont(new java.awt.Font("Times New Roman", 0, 12)); // NOI18N
        jtfMaeFuncionario.setEnabled(false);

        jlPaiFuncionario.setFont(new java.awt.Font("Times New Roman", 1, 12)); // NOI18N
        jlPaiFuncionario.setText("Pai");

        jtfPaiFuncionario.setFont(new java.awt.Font("Times New Roman", 0, 12)); // NOI18N
        jtfPaiFuncionario.setEnabled(false);

        javax.swing.GroupLayout jpDadosPessoaisFuncionarioLayout = new javax.swing.GroupLayout(jpDadosPessoaisFuncionario);
        jpDadosPessoaisFuncionario.setLayout(jpDadosPessoaisFuncionarioLayout);
        jpDadosPessoaisFuncionarioLayout.setHorizontalGroup(
            jpDadosPessoaisFuncionarioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jpDadosPessoaisFuncionarioLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jpDadosPessoaisFuncionarioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jlNomeFuncionario)
                    .addComponent(jtfnomeFuncionario, javax.swing.GroupLayout.PREFERRED_SIZE, 516, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jpDadosPessoaisFuncionarioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                        .addGroup(jpDadosPessoaisFuncionarioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jlSexoFuncionario)
                            .addComponent(jcbSexoFuncionario, javax.swing.GroupLayout.PREFERRED_SIZE, 102, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGroup(jpDadosPessoaisFuncionarioLayout.createSequentialGroup()
                            .addGroup(jpDadosPessoaisFuncionarioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                .addComponent(jlCpfFuncionario, javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(jtfCpfFuncionario, javax.swing.GroupLayout.PREFERRED_SIZE, 140, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                            .addGroup(jpDadosPessoaisFuncionarioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addGroup(jpDadosPessoaisFuncionarioLayout.createSequentialGroup()
                                    .addGap(4, 4, 4)
                                    .addComponent(jlRgFuncionario))
                                .addComponent(jtfRgFuncionario, javax.swing.GroupLayout.PREFERRED_SIZE, 140, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                            .addGroup(jpDadosPessoaisFuncionarioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(jlDataNascimentoFuncionario)
                                .addComponent(jtfDataNascimentoFuncionario, javax.swing.GroupLayout.PREFERRED_SIZE, 125, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                            .addGroup(jpDadosPessoaisFuncionarioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(jlPisNitFuncionario)
                                .addComponent(jtfPisNitFuncionario, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE))))
                    .addGroup(jpDadosPessoaisFuncionarioLayout.createSequentialGroup()
                        .addGroup(jpDadosPessoaisFuncionarioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jlMaeFuncionario)
                            .addComponent(jtfMaeFuncionario, javax.swing.GroupLayout.PREFERRED_SIZE, 290, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(jpDadosPessoaisFuncionarioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jlPaiFuncionario)
                            .addComponent(jtfPaiFuncionario))))
                .addGap(0, 14, Short.MAX_VALUE))
        );
        jpDadosPessoaisFuncionarioLayout.setVerticalGroup(
            jpDadosPessoaisFuncionarioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jpDadosPessoaisFuncionarioLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jpDadosPessoaisFuncionarioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jpDadosPessoaisFuncionarioLayout.createSequentialGroup()
                        .addComponent(jlSexoFuncionario)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jcbSexoFuncionario, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jpDadosPessoaisFuncionarioLayout.createSequentialGroup()
                        .addComponent(jlNomeFuncionario)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jtfnomeFuncionario, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jpDadosPessoaisFuncionarioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jpDadosPessoaisFuncionarioLayout.createSequentialGroup()
                        .addComponent(jlCpfFuncionario)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jtfCpfFuncionario, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jtfRgFuncionario, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jpDadosPessoaisFuncionarioLayout.createSequentialGroup()
                        .addComponent(jlRgFuncionario)
                        .addGap(26, 26, 26))
                    .addGroup(jpDadosPessoaisFuncionarioLayout.createSequentialGroup()
                        .addComponent(jlDataNascimentoFuncionario)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jtfDataNascimentoFuncionario, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jpDadosPessoaisFuncionarioLayout.createSequentialGroup()
                        .addComponent(jlPisNitFuncionario)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jtfPisNitFuncionario, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(11, 11, 11)
                .addGroup(jpDadosPessoaisFuncionarioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jpDadosPessoaisFuncionarioLayout.createSequentialGroup()
                        .addComponent(jlPaiFuncionario)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jtfPaiFuncionario, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jpDadosPessoaisFuncionarioLayout.createSequentialGroup()
                        .addComponent(jlMaeFuncionario)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jtfMaeFuncionario, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(13, Short.MAX_VALUE))
        );

        jpContatoFuncionario.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Contato", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Times New Roman", 1, 12))); // NOI18N

        jpEnderecoFuncionario.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Endereço", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Times New Roman", 1, 12))); // NOI18N

        jlLogadouroFuncionario.setFont(new java.awt.Font("Times New Roman", 1, 12)); // NOI18N
        jlLogadouroFuncionario.setText("Logadouro");

        jtfLogadouroFuncionario.setFont(new java.awt.Font("Times New Roman", 0, 12)); // NOI18N
        jtfLogadouroFuncionario.setEnabled(false);

        jlNumeroEndFuncionario.setFont(new java.awt.Font("Times New Roman", 1, 12)); // NOI18N
        jlNumeroEndFuncionario.setText("Número");

        jtfNumeroEndFuncionario.setFont(new java.awt.Font("Times New Roman", 0, 12)); // NOI18N
        jtfNumeroEndFuncionario.setEnabled(false);

        jlComplementoEndFuncionario.setFont(new java.awt.Font("Times New Roman", 1, 12)); // NOI18N
        jlComplementoEndFuncionario.setText("Complemento");

        jtfComplementoEndFuncionario.setFont(new java.awt.Font("Times New Roman", 0, 12)); // NOI18N
        jtfComplementoEndFuncionario.setEnabled(false);

        jlBairroEndFuncionario.setFont(new java.awt.Font("Times New Roman", 1, 12)); // NOI18N
        jlBairroEndFuncionario.setText("Bairro");

        jtfBairroEndFuncionario.setFont(new java.awt.Font("Times New Roman", 0, 12)); // NOI18N
        jtfBairroEndFuncionario.setEnabled(false);

        jlCepEndFuncionario.setFont(new java.awt.Font("Times New Roman", 1, 12)); // NOI18N
        jlCepEndFuncionario.setText("CEP");

        jtfCepEndFuncionario.setFont(new java.awt.Font("Times New Roman", 0, 12)); // NOI18N
        jtfCepEndFuncionario.setEnabled(false);

        jlCidadeEndFuncionario.setFont(new java.awt.Font("Times New Roman", 1, 12)); // NOI18N
        jlCidadeEndFuncionario.setText("Cidade");

        jtfCidadeEndFuncionario.setFont(new java.awt.Font("Times New Roman", 0, 12)); // NOI18N
        jtfCidadeEndFuncionario.setEnabled(false);

        jlEstadoEndFuncionario.setFont(new java.awt.Font("Times New Roman", 1, 12)); // NOI18N
        jlEstadoEndFuncionario.setText("Estado");

        jtfEstadoEndFuncionario.setFont(new java.awt.Font("Times New Roman", 0, 12)); // NOI18N
        jtfEstadoEndFuncionario.setEnabled(false);

        javax.swing.GroupLayout jpEnderecoFuncionarioLayout = new javax.swing.GroupLayout(jpEnderecoFuncionario);
        jpEnderecoFuncionario.setLayout(jpEnderecoFuncionarioLayout);
        jpEnderecoFuncionarioLayout.setHorizontalGroup(
            jpEnderecoFuncionarioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jpEnderecoFuncionarioLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jpEnderecoFuncionarioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jpEnderecoFuncionarioLayout.createSequentialGroup()
                        .addGroup(jpEnderecoFuncionarioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jlLogadouroFuncionario, javax.swing.GroupLayout.PREFERRED_SIZE, 79, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jtfLogadouroFuncionario, javax.swing.GroupLayout.PREFERRED_SIZE, 361, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(jpEnderecoFuncionarioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jlNumeroEndFuncionario, javax.swing.GroupLayout.PREFERRED_SIZE, 79, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jtfNumeroEndFuncionario, javax.swing.GroupLayout.PREFERRED_SIZE, 107, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(jpEnderecoFuncionarioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jlComplementoEndFuncionario, javax.swing.GroupLayout.PREFERRED_SIZE, 79, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jtfComplementoEndFuncionario, javax.swing.GroupLayout.PREFERRED_SIZE, 107, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(jpEnderecoFuncionarioLayout.createSequentialGroup()
                        .addGroup(jpEnderecoFuncionarioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jlBairroEndFuncionario, javax.swing.GroupLayout.PREFERRED_SIZE, 79, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jtfBairroEndFuncionario, javax.swing.GroupLayout.PREFERRED_SIZE, 166, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(jpEnderecoFuncionarioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jlCepEndFuncionario, javax.swing.GroupLayout.PREFERRED_SIZE, 79, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jtfCepEndFuncionario, javax.swing.GroupLayout.PREFERRED_SIZE, 128, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(jpEnderecoFuncionarioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jlCidadeEndFuncionario, javax.swing.GroupLayout.PREFERRED_SIZE, 79, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jtfCidadeEndFuncionario, javax.swing.GroupLayout.PREFERRED_SIZE, 136, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(jpEnderecoFuncionarioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jpEnderecoFuncionarioLayout.createSequentialGroup()
                                .addComponent(jlEstadoEndFuncionario, javax.swing.GroupLayout.PREFERRED_SIZE, 79, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 66, Short.MAX_VALUE))
                            .addComponent(jtfEstadoEndFuncionario))))
                .addContainerGap())
        );
        jpEnderecoFuncionarioLayout.setVerticalGroup(
            jpEnderecoFuncionarioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jpEnderecoFuncionarioLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jpEnderecoFuncionarioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jpEnderecoFuncionarioLayout.createSequentialGroup()
                        .addComponent(jlLogadouroFuncionario)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jtfLogadouroFuncionario, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jpEnderecoFuncionarioLayout.createSequentialGroup()
                        .addComponent(jlNumeroEndFuncionario)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jtfNumeroEndFuncionario, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jpEnderecoFuncionarioLayout.createSequentialGroup()
                        .addComponent(jlComplementoEndFuncionario)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jtfComplementoEndFuncionario, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jpEnderecoFuncionarioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jpEnderecoFuncionarioLayout.createSequentialGroup()
                        .addComponent(jlEstadoEndFuncionario)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jtfEstadoEndFuncionario, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jpEnderecoFuncionarioLayout.createSequentialGroup()
                        .addComponent(jlBairroEndFuncionario)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jtfBairroEndFuncionario, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jpEnderecoFuncionarioLayout.createSequentialGroup()
                        .addComponent(jlCepEndFuncionario)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jtfCepEndFuncionario, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jpEnderecoFuncionarioLayout.createSequentialGroup()
                        .addComponent(jlCidadeEndFuncionario)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jtfCidadeEndFuncionario, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jpEmailFuncionario.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "E-mail", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Times New Roman", 1, 12))); // NOI18N

        jtfEmailFuncionario.setFont(new java.awt.Font("Times New Roman", 0, 12)); // NOI18N
        jtfEmailFuncionario.setEnabled(false);

        javax.swing.GroupLayout jpEmailFuncionarioLayout = new javax.swing.GroupLayout(jpEmailFuncionario);
        jpEmailFuncionario.setLayout(jpEmailFuncionarioLayout);
        jpEmailFuncionarioLayout.setHorizontalGroup(
            jpEmailFuncionarioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jpEmailFuncionarioLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jtfEmailFuncionario, javax.swing.GroupLayout.PREFERRED_SIZE, 341, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(11, Short.MAX_VALUE))
        );
        jpEmailFuncionarioLayout.setVerticalGroup(
            jpEmailFuncionarioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jtfEmailFuncionario, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        jpTelefoneFuncionario.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Telefone", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Times New Roman", 1, 12))); // NOI18N

        jtfTelefoneFuncionario.setFont(new java.awt.Font("Times New Roman", 0, 12)); // NOI18N
        jtfTelefoneFuncionario.setEnabled(false);

        javax.swing.GroupLayout jpTelefoneFuncionarioLayout = new javax.swing.GroupLayout(jpTelefoneFuncionario);
        jpTelefoneFuncionario.setLayout(jpTelefoneFuncionarioLayout);
        jpTelefoneFuncionarioLayout.setHorizontalGroup(
            jpTelefoneFuncionarioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jpTelefoneFuncionarioLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jtfTelefoneFuncionario)
                .addContainerGap())
        );
        jpTelefoneFuncionarioLayout.setVerticalGroup(
            jpTelefoneFuncionarioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jtfTelefoneFuncionario, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        javax.swing.GroupLayout jpContatoFuncionarioLayout = new javax.swing.GroupLayout(jpContatoFuncionario);
        jpContatoFuncionario.setLayout(jpContatoFuncionarioLayout);
        jpContatoFuncionarioLayout.setHorizontalGroup(
            jpContatoFuncionarioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jpContatoFuncionarioLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jpContatoFuncionarioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jpEnderecoFuncionario, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jpContatoFuncionarioLayout.createSequentialGroup()
                        .addComponent(jpEmailFuncionario, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(jpTelefoneFuncionario, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                .addGap(0, 0, Short.MAX_VALUE))
        );
        jpContatoFuncionarioLayout.setVerticalGroup(
            jpContatoFuncionarioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jpContatoFuncionarioLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jpEnderecoFuncionario, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jpContatoFuncionarioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jpEmailFuncionario, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jpTelefoneFuncionario, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jpVinculoFuncionario.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Vínculo", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Times New Roman", 1, 12))); // NOI18N

        jtfDataInicioContratoFuncionario.setFont(new java.awt.Font("Times New Roman", 0, 12)); // NOI18N
        jtfDataInicioContratoFuncionario.setEnabled(false);

        jlDataInicioContratoFuncionario.setFont(new java.awt.Font("Times New Roman", 1, 12)); // NOI18N
        jlDataInicioContratoFuncionario.setText("Data de Início Contrato");

        jlDataFimContratoFuncionario.setFont(new java.awt.Font("Times New Roman", 1, 12)); // NOI18N
        jlDataFimContratoFuncionario.setText("Data do Fim do Contrato");

        jtfDataFimContratoFuncionario.setFont(new java.awt.Font("Times New Roman", 0, 12)); // NOI18N
        jtfDataFimContratoFuncionario.setEnabled(false);

        jlSalarioFuncionario.setFont(new java.awt.Font("Times New Roman", 1, 12)); // NOI18N
        jlSalarioFuncionario.setText("Salário");

        jtfSalarioFuncionario.setFont(new java.awt.Font("Times New Roman", 0, 12)); // NOI18N
        jtfSalarioFuncionario.setEnabled(false);

        jlCargoFuncionario.setFont(new java.awt.Font("Times New Roman", 1, 12)); // NOI18N
        jlCargoFuncionario.setText("Cargo");

        jtfCargoFuncionario.setFont(new java.awt.Font("Times New Roman", 0, 12)); // NOI18N
        jtfCargoFuncionario.setEnabled(false);

        javax.swing.GroupLayout jpVinculoFuncionarioLayout = new javax.swing.GroupLayout(jpVinculoFuncionario);
        jpVinculoFuncionario.setLayout(jpVinculoFuncionarioLayout);
        jpVinculoFuncionarioLayout.setHorizontalGroup(
            jpVinculoFuncionarioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jpVinculoFuncionarioLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jpVinculoFuncionarioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jlCargoFuncionario)
                    .addComponent(jtfCargoFuncionario, javax.swing.GroupLayout.PREFERRED_SIZE, 241, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jpVinculoFuncionarioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jlSalarioFuncionario, javax.swing.GroupLayout.PREFERRED_SIZE, 79, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jtfSalarioFuncionario, javax.swing.GroupLayout.PREFERRED_SIZE, 112, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jpVinculoFuncionarioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jlDataInicioContratoFuncionario, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jtfDataInicioContratoFuncionario))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jpVinculoFuncionarioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jlDataFimContratoFuncionario, javax.swing.GroupLayout.DEFAULT_SIZE, 137, Short.MAX_VALUE)
                    .addComponent(jtfDataFimContratoFuncionario))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jpVinculoFuncionarioLayout.setVerticalGroup(
            jpVinculoFuncionarioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jpVinculoFuncionarioLayout.createSequentialGroup()
                .addGroup(jpVinculoFuncionarioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jpVinculoFuncionarioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                        .addGroup(jpVinculoFuncionarioLayout.createSequentialGroup()
                            .addComponent(jlCargoFuncionario)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                            .addComponent(jtfCargoFuncionario, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGroup(jpVinculoFuncionarioLayout.createSequentialGroup()
                            .addComponent(jlSalarioFuncionario)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                            .addComponent(jtfSalarioFuncionario, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGroup(jpVinculoFuncionarioLayout.createSequentialGroup()
                            .addComponent(jlDataInicioContratoFuncionario)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                            .addComponent(jtfDataInicioContratoFuncionario, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(jpVinculoFuncionarioLayout.createSequentialGroup()
                        .addComponent(jlDataFimContratoFuncionario)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jtfDataFimContratoFuncionario, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jpSistemaFuncionario.setBorder(javax.swing.BorderFactory.createTitledBorder(javax.swing.BorderFactory.createTitledBorder(null, "Sistema", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Times New Roman", 1, 12)))); // NOI18N

        jlLoginFuncionario.setFont(new java.awt.Font("Times New Roman", 1, 12)); // NOI18N
        jlLoginFuncionario.setText("Login");

        jtfLoginFuncionario.setFont(new java.awt.Font("Times New Roman", 0, 12)); // NOI18N
        jtfLoginFuncionario.setEnabled(false);

        jlSenhaFuncionario.setFont(new java.awt.Font("Times New Roman", 1, 12)); // NOI18N
        jlSenhaFuncionario.setText("Senha");

        jtfSenhaFuncionario.setFont(new java.awt.Font("Times New Roman", 0, 12)); // NOI18N
        jtfSenhaFuncionario.setEnabled(false);

        javax.swing.GroupLayout jpSistemaFuncionarioLayout = new javax.swing.GroupLayout(jpSistemaFuncionario);
        jpSistemaFuncionario.setLayout(jpSistemaFuncionarioLayout);
        jpSistemaFuncionarioLayout.setHorizontalGroup(
            jpSistemaFuncionarioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jpSistemaFuncionarioLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jpSistemaFuncionarioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jlLoginFuncionario, javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jtfLoginFuncionario, javax.swing.GroupLayout.PREFERRED_SIZE, 163, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jpSistemaFuncionarioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jlSenhaFuncionario, javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jtfSenhaFuncionario, javax.swing.GroupLayout.PREFERRED_SIZE, 163, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jpSistemaFuncionarioLayout.setVerticalGroup(
            jpSistemaFuncionarioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jpSistemaFuncionarioLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jpSistemaFuncionarioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jpSistemaFuncionarioLayout.createSequentialGroup()
                        .addComponent(jlSenhaFuncionario)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jtfSenhaFuncionario, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jpSistemaFuncionarioLayout.createSequentialGroup()
                        .addComponent(jlLoginFuncionario)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jtfLoginFuncionario, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jbEditarFuncionario.setFont(new java.awt.Font("Times New Roman", 1, 12)); // NOI18N
        jbEditarFuncionario.setIcon(new javax.swing.ImageIcon(getClass().getResource("/IMAGENS/1editar.png"))); // NOI18N
        jbEditarFuncionario.setText("  Editar");
        jbEditarFuncionario.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbEditarFuncionarioActionPerformed(evt);
            }
        });

        jbSalvarFuncionario.setFont(new java.awt.Font("Times New Roman", 1, 12)); // NOI18N
        jbSalvarFuncionario.setIcon(new javax.swing.ImageIcon(getClass().getResource("/IMAGENS/1salvar.png"))); // NOI18N
        jbSalvarFuncionario.setText("  Salvar");
        jbSalvarFuncionario.setEnabled(false);
        jbSalvarFuncionario.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbSalvarFuncionarioActionPerformed(evt);
            }
        });

        jbCancelarFuncionario1.setFont(new java.awt.Font("Times New Roman", 1, 12)); // NOI18N
        jbCancelarFuncionario1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/IMAGENS/1excluir.png"))); // NOI18N
        jbCancelarFuncionario1.setText("  Cancelar");
        jbCancelarFuncionario1.setEnabled(false);
        jbCancelarFuncionario1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbCancelarFuncionario1ActionPerformed(evt);
            }
        });

        jbExcluirFuncionario.setFont(new java.awt.Font("Times New Roman", 1, 12)); // NOI18N
        jbExcluirFuncionario.setIcon(new javax.swing.ImageIcon(getClass().getResource("/IMAGENS/1apagar.png"))); // NOI18N
        jbExcluirFuncionario.setText("  Excluir");
        jbExcluirFuncionario.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbExcluirFuncionarioActionPerformed(evt);
            }
        });

        jtFuncionarios.setFont(new java.awt.Font("Times New Roman", 0, 12)); // NOI18N
        jtFuncionarios.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null}
            },
            new String [] {
                "CÓDIGO", "NOME", "CPF"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.String.class, java.lang.String.class, java.lang.String.class
            };
            boolean[] canEdit = new boolean [] {
                false, false, false
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jtFuncionarios.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jtFuncionariosMouseClicked(evt);
            }
        });
        jScrollPane2.setViewportView(jtFuncionarios);

        jpDadosFuncionarios.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Pesquisar", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Times New Roman", 1, 12))); // NOI18N

        jtfCodigoFunconario.setFont(new java.awt.Font("Times New Roman", 0, 12)); // NOI18N

        javax.swing.GroupLayout jpDadosFuncionariosLayout = new javax.swing.GroupLayout(jpDadosFuncionarios);
        jpDadosFuncionarios.setLayout(jpDadosFuncionariosLayout);
        jpDadosFuncionariosLayout.setHorizontalGroup(
            jpDadosFuncionariosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jpDadosFuncionariosLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jtfCodigoFunconario)
                .addContainerGap())
        );
        jpDadosFuncionariosLayout.setVerticalGroup(
            jpDadosFuncionariosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jpDadosFuncionariosLayout.createSequentialGroup()
                .addComponent(jtfCodigoFunconario, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 9, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout jpFuncionariosLayout = new javax.swing.GroupLayout(jpFuncionarios);
        jpFuncionarios.setLayout(jpFuncionariosLayout);
        jpFuncionariosLayout.setHorizontalGroup(
            jpFuncionariosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jpFuncionariosLayout.createSequentialGroup()
                .addGroup(jpFuncionariosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jpDadosFuncionarios, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jScrollPane2, javax.swing.GroupLayout.DEFAULT_SIZE, 404, Short.MAX_VALUE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jpFuncionariosLayout.setVerticalGroup(
            jpFuncionariosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jpFuncionariosLayout.createSequentialGroup()
                .addComponent(jpDadosFuncionarios, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 599, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jbNovoFuncionario.setFont(new java.awt.Font("Times New Roman", 1, 12)); // NOI18N
        jbNovoFuncionario.setIcon(new javax.swing.ImageIcon(getClass().getResource("/IMAGENS/1novo.png"))); // NOI18N
        jbNovoFuncionario.setText("  Novo");
        jbNovoFuncionario.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbNovoFuncionarioActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel9Layout = new javax.swing.GroupLayout(jPanel9);
        jPanel9.setLayout(jPanel9Layout);
        jPanel9Layout.setHorizontalGroup(
            jPanel9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel9Layout.createSequentialGroup()
                .addGroup(jPanel9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel9Layout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(jPanel9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jpSistemaFuncionario, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(jPanel9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                .addComponent(jpVinculoFuncionario, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 671, Short.MAX_VALUE)
                                .addComponent(jpContatoFuncionario, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(jpDadosPessoaisFuncionario, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel9Layout.createSequentialGroup()
                                    .addComponent(jlCodigoFuncionário)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                    .addComponent(jlCodigoNumFuncionario)))))
                    .addGroup(jPanel9Layout.createSequentialGroup()
                        .addGap(46, 46, 46)
                        .addComponent(jbNovoFuncionario, javax.swing.GroupLayout.PREFERRED_SIZE, 118, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jbEditarFuncionario, javax.swing.GroupLayout.PREFERRED_SIZE, 115, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jbSalvarFuncionario, javax.swing.GroupLayout.PREFERRED_SIZE, 123, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jbCancelarFuncionario1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jbExcluirFuncionario)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jpFuncionarios, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(15, Short.MAX_VALUE))
        );
        jPanel9Layout.setVerticalGroup(
            jPanel9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel9Layout.createSequentialGroup()
                .addGap(7, 7, 7)
                .addGroup(jPanel9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jlCodigoFuncionário)
                    .addComponent(jlCodigoNumFuncionario))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel9Layout.createSequentialGroup()
                        .addComponent(jpDadosPessoaisFuncionario, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(10, 10, 10)
                        .addComponent(jpContatoFuncionario, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jpVinculoFuncionario, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jpSistemaFuncionario, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(jPanel9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jbSalvarFuncionario)
                            .addComponent(jbCancelarFuncionario1)
                            .addComponent(jbExcluirFuncionario)
                            .addComponent(jbEditarFuncionario)
                            .addComponent(jbNovoFuncionario)))
                    .addComponent(jpFuncionarios, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jScrollPane1.setViewportView(jPanel9);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane1)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 604, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jbEditarFuncionarioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbEditarFuncionarioActionPerformed
        jtfnomeFuncionario.setEnabled(true);
        jcbSexoFuncionario.setEnabled(true);
        jtfCpfFuncionario.setEnabled(true);
        jtfRgFuncionario.setEnabled(true);
        jtfDataNascimentoFuncionario.setEnabled(true);
        jtfPisNitFuncionario.setEnabled(true);
        jtfMaeFuncionario.setEnabled(true);
        jtfPaiFuncionario.setEnabled(true);
        jtfLogadouroFuncionario.setEnabled(true);
        jtfNumeroEndFuncionario.setEnabled(true);
        jtfComplementoEndFuncionario.setEnabled(true);
        jtfBairroEndFuncionario.setEnabled(true);
        jtfCepEndFuncionario.setEnabled(true);
        jtfCidadeEndFuncionario.setEnabled(true);
        jtfEstadoEndFuncionario.setEnabled(true);
        jtfEmailFuncionario.setEnabled(true);
        jtfTelefoneFuncionario.setEnabled(true);
        jtfCargoFuncionario.setEnabled(true);
        jtfSalarioFuncionario.setEnabled(true);
        jtfDataInicioContratoFuncionario.setEnabled(true);
        jtfDataFimContratoFuncionario.setEnabled(true);
        jtfLoginFuncionario.setEnabled(true);
        jtfSenhaFuncionario.setEnabled(true);
        jbEditarFuncionario.setEnabled(false);
        jbSalvarFuncionario.setEnabled(true);
        jbCancelarFuncionario1.setEnabled(true);
        jbExcluirFuncionario.setEnabled(false);
    }//GEN-LAST:event_jbEditarFuncionarioActionPerformed

    private void jbSalvarFuncionarioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbSalvarFuncionarioActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jbSalvarFuncionarioActionPerformed

    private void jbCancelarFuncionario1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbCancelarFuncionario1ActionPerformed
        jtfnomeFuncionario.setEnabled(false);
        jcbSexoFuncionario.setEnabled(false);
        jtfCpfFuncionario.setEnabled(false);
        jtfRgFuncionario.setEnabled(false);
        jtfDataNascimentoFuncionario.setEnabled(false);
        jtfPisNitFuncionario.setEnabled(false);
        jtfMaeFuncionario.setEnabled(false);
        jtfPaiFuncionario.setEnabled(false);
        jtfLogadouroFuncionario.setEnabled(false);
        jtfNumeroEndFuncionario.setEnabled(false);
        jtfComplementoEndFuncionario.setEnabled(false);
        jtfBairroEndFuncionario.setEnabled(false);
        jtfCepEndFuncionario.setEnabled(false);
        jtfCidadeEndFuncionario.setEnabled(false);
        jtfEstadoEndFuncionario.setEnabled(false);
        jtfEmailFuncionario.setEnabled(false);
        jtfTelefoneFuncionario.setEnabled(false);
        jtfCargoFuncionario.setEnabled(false);
        jtfSalarioFuncionario.setEnabled(false);
        jtfDataInicioContratoFuncionario.setEnabled(false);
        jtfDataFimContratoFuncionario.setEnabled(false);
        jtfLoginFuncionario.setEnabled(false);
        jtfSenhaFuncionario.setEnabled(false);
        jbEditarFuncionario.setEnabled(true);
        jbSalvarFuncionario.setEnabled(false);
        jbCancelarFuncionario1.setEnabled(false);
        jbExcluirFuncionario.setEnabled(true);
    }//GEN-LAST:event_jbCancelarFuncionario1ActionPerformed

    private void jbExcluirFuncionarioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbExcluirFuncionarioActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jbExcluirFuncionarioActionPerformed

    private void jtFuncionariosMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jtFuncionariosMouseClicked
//        jbVisualizarFuncionario.setEnabled(true);
    }//GEN-LAST:event_jtFuncionariosMouseClicked

    private void jbNovoFuncionarioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbNovoFuncionarioActionPerformed
//        JIFNovoCadastroFuncionario janela = new JIFNovoCadastroFuncionario();
//        JFPrincipal.jdpPrincipal1.add(janela);
//        janela.setVisible(true);
//        System.out.println("VIEW.JIFFuncionarios.jbNovoFuncionarioActionPerformed()");
    }//GEN-LAST:event_jbNovoFuncionarioActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel jPanel9;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JButton jbCancelarFuncionario1;
    private javax.swing.JButton jbEditarFuncionario;
    private javax.swing.JButton jbExcluirFuncionario;
    private javax.swing.JButton jbNovoFuncionario;
    private javax.swing.JButton jbSalvarFuncionario;
    private javax.swing.JComboBox<String> jcbSexoFuncionario;
    private javax.swing.JLabel jlBairroEndFuncionario;
    private javax.swing.JLabel jlCargoFuncionario;
    private javax.swing.JLabel jlCepEndFuncionario;
    private javax.swing.JLabel jlCidadeEndFuncionario;
    private javax.swing.JLabel jlCodigoFuncionário;
    private javax.swing.JLabel jlCodigoNumFuncionario;
    private javax.swing.JLabel jlComplementoEndFuncionario;
    private javax.swing.JLabel jlCpfFuncionario;
    private javax.swing.JLabel jlDataFimContratoFuncionario;
    private javax.swing.JLabel jlDataInicioContratoFuncionario;
    private javax.swing.JLabel jlDataNascimentoFuncionario;
    private javax.swing.JLabel jlEstadoEndFuncionario;
    private javax.swing.JLabel jlLogadouroFuncionario;
    private javax.swing.JLabel jlLoginFuncionario;
    private javax.swing.JLabel jlMaeFuncionario;
    private javax.swing.JLabel jlNomeFuncionario;
    private javax.swing.JLabel jlNumeroEndFuncionario;
    private javax.swing.JLabel jlPaiFuncionario;
    private javax.swing.JLabel jlPisNitFuncionario;
    private javax.swing.JLabel jlRgFuncionario;
    private javax.swing.JLabel jlSalarioFuncionario;
    private javax.swing.JLabel jlSenhaFuncionario;
    private javax.swing.JLabel jlSexoFuncionario;
    private javax.swing.JPanel jpContatoFuncionario;
    private javax.swing.JPanel jpDadosFuncionarios;
    private javax.swing.JPanel jpDadosPessoaisFuncionario;
    private javax.swing.JPanel jpEmailFuncionario;
    private javax.swing.JPanel jpEnderecoFuncionario;
    private javax.swing.JPanel jpFuncionarios;
    private javax.swing.JPanel jpSistemaFuncionario;
    private javax.swing.JPanel jpTelefoneFuncionario;
    private javax.swing.JPanel jpVinculoFuncionario;
    private javax.swing.JTable jtFuncionarios;
    private javax.swing.JTextField jtfBairroEndFuncionario;
    private javax.swing.JTextField jtfCargoFuncionario;
    private javax.swing.JTextField jtfCepEndFuncionario;
    private javax.swing.JTextField jtfCidadeEndFuncionario;
    private javax.swing.JTextField jtfCodigoFunconario;
    private javax.swing.JTextField jtfComplementoEndFuncionario;
    private javax.swing.JTextField jtfCpfFuncionario;
    private javax.swing.JTextField jtfDataFimContratoFuncionario;
    private javax.swing.JTextField jtfDataInicioContratoFuncionario;
    private javax.swing.JTextField jtfDataNascimentoFuncionario;
    private javax.swing.JTextField jtfEmailFuncionario;
    private javax.swing.JTextField jtfEstadoEndFuncionario;
    private javax.swing.JTextField jtfLogadouroFuncionario;
    private javax.swing.JTextField jtfLoginFuncionario;
    private javax.swing.JTextField jtfMaeFuncionario;
    private javax.swing.JTextField jtfNumeroEndFuncionario;
    private javax.swing.JTextField jtfPaiFuncionario;
    private javax.swing.JTextField jtfPisNitFuncionario;
    private javax.swing.JTextField jtfRgFuncionario;
    private javax.swing.JTextField jtfSalarioFuncionario;
    private javax.swing.JTextField jtfSenhaFuncionario;
    private javax.swing.JTextField jtfTelefoneFuncionario;
    private javax.swing.JTextField jtfnomeFuncionario;
    // End of variables declaration//GEN-END:variables
}
