/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package VIEW;

import DATA.LancarEntradaData;
import DATA.LancarVendaData;
import MODEL.LancarEntradaModel;
import MODEL.LancarVendaModel;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;

/**
 *
 * @author Roberto Junior Akira
 */
public class JIFLancarVenda extends javax.swing.JInternalFrame {
    private LancarVendaModel obj;
    private LancarVendaData DAO;
    /**
     * Creates new form JIFLancarVenda
     */
    public JIFLancarVenda() {
        initComponents();
        obj = new LancarVendaModel();
        try {
            DAO = new LancarVendaData();
        } catch (Exception ex) {
            Logger.getLogger(JIFLancarVenda.class.getName()).log(Level.SEVERE, null, ex);
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        jpVendaFisico = new javax.swing.JPanel();
        jpClienteFisico = new javax.swing.JPanel();
        jlCnpjCpfCliente = new javax.swing.JLabel();
        jtfCnpjCpfCliente = new javax.swing.JTextField();
        jbConsultaCNPJCpfCliente = new javax.swing.JButton();
        jlRazaoSocialNomeCliente = new javax.swing.JLabel();
        jtfRazaoSocialNomeCliente = new javax.swing.JTextField();
        jbConsultaRazaoSocialNomeCliente = new javax.swing.JButton();
        jpVenda = new javax.swing.JPanel();
        jlCodigoVendaProd = new javax.swing.JLabel();
        jtfCodigoVendaProd = new javax.swing.JTextField();
        jbConsultaCodigoVendaProd = new javax.swing.JButton();
        jlDescricaoVendaProd = new javax.swing.JLabel();
        jtfDescricaoProdVenda = new javax.swing.JTextField();
        jbConsultaDescricaoVendaProd = new javax.swing.JButton();
        jlUnidMedidaVendaProd = new javax.swing.JLabel();
        jlQuantidadeVendaProd = new javax.swing.JLabel();
        jtfQuantidadeVendaProd = new javax.swing.JTextField();
        jbNovoVendaProd = new javax.swing.JButton();
        jbEditarVendaProd = new javax.swing.JButton();
        jbIncluirVendaProd = new javax.swing.JButton();
        jlValorUnitVendaProd = new javax.swing.JLabel();
        jtfValorUnitVendaProd = new javax.swing.JTextField();
        jbExcluirVendaProd = new javax.swing.JButton();
        jScrollPane16 = new javax.swing.JScrollPane();
        jtVendaProd = new javax.swing.JTable();
        jlValorTotalVendaProd = new javax.swing.JLabel();
        jtfValorTotalVendaProd = new javax.swing.JTextField();
        jbSalvarVenda = new javax.swing.JButton();
        jbCancelarVenda = new javax.swing.JButton();
        jbImprimirVenda = new javax.swing.JButton();
        jlIdVenda = new javax.swing.JLabel();
        jlNumIdVenda = new javax.swing.JLabel();
        jpValorTotalVenda = new javax.swing.JPanel();
        jlValorTotalVenda = new javax.swing.JLabel();
        jtfValorTotalVenda = new javax.swing.JTextField();
        jlDataVenda = new javax.swing.JLabel();
        jtfDataVenda = new javax.swing.JTextField();
        jtfUnidMedida = new javax.swing.JTextField();

        setClosable(true);
        setIconifiable(true);

        jpVendaFisico.setBackground(new java.awt.Color(0, 102, 153));
        jpVendaFisico.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "VENDA", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Times New Roman", 1, 12))); // NOI18N

        jpClienteFisico.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Cliente", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Times New Roman", 1, 12))); // NOI18N

        jlCnpjCpfCliente.setFont(new java.awt.Font("Times New Roman", 1, 12)); // NOI18N
        jlCnpjCpfCliente.setText("CNPJ / CPF");

        jtfCnpjCpfCliente.setFont(new java.awt.Font("Times New Roman", 0, 12)); // NOI18N

        jbConsultaCNPJCpfCliente.setIcon(new javax.swing.ImageIcon(getClass().getResource("/IMAGENS/lupa.png"))); // NOI18N

        jlRazaoSocialNomeCliente.setFont(new java.awt.Font("Times New Roman", 1, 12)); // NOI18N
        jlRazaoSocialNomeCliente.setText("Razão Social / Nome");

        jtfRazaoSocialNomeCliente.setFont(new java.awt.Font("Times New Roman", 0, 12)); // NOI18N

        jbConsultaRazaoSocialNomeCliente.setIcon(new javax.swing.ImageIcon(getClass().getResource("/IMAGENS/lupa.png"))); // NOI18N

        javax.swing.GroupLayout jpClienteFisicoLayout = new javax.swing.GroupLayout(jpClienteFisico);
        jpClienteFisico.setLayout(jpClienteFisicoLayout);
        jpClienteFisicoLayout.setHorizontalGroup(
            jpClienteFisicoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jpClienteFisicoLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jpClienteFisicoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jlCnpjCpfCliente)
                    .addGroup(jpClienteFisicoLayout.createSequentialGroup()
                        .addComponent(jtfCnpjCpfCliente, javax.swing.GroupLayout.PREFERRED_SIZE, 170, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jbConsultaCNPJCpfCliente, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(18, 18, 18)
                .addGroup(jpClienteFisicoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jpClienteFisicoLayout.createSequentialGroup()
                        .addComponent(jlRazaoSocialNomeCliente)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(jpClienteFisicoLayout.createSequentialGroup()
                        .addComponent(jtfRazaoSocialNomeCliente, javax.swing.GroupLayout.DEFAULT_SIZE, 339, Short.MAX_VALUE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jbConsultaRazaoSocialNomeCliente, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap())
        );
        jpClienteFisicoLayout.setVerticalGroup(
            jpClienteFisicoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jpClienteFisicoLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jpClienteFisicoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jpClienteFisicoLayout.createSequentialGroup()
                        .addComponent(jlRazaoSocialNomeCliente)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jtfRazaoSocialNomeCliente, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jpClienteFisicoLayout.createSequentialGroup()
                        .addComponent(jlCnpjCpfCliente)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jtfCnpjCpfCliente, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jbConsultaCNPJCpfCliente, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jbConsultaRazaoSocialNomeCliente, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jpVenda.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Venda", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Times New Roman", 1, 12))); // NOI18N

        jlCodigoVendaProd.setFont(new java.awt.Font("Times New Roman", 1, 12)); // NOI18N
        jlCodigoVendaProd.setText("Código");

        jtfCodigoVendaProd.setFont(new java.awt.Font("Times New Roman", 0, 12)); // NOI18N
        jtfCodigoVendaProd.setEnabled(false);

        jbConsultaCodigoVendaProd.setIcon(new javax.swing.ImageIcon(getClass().getResource("/IMAGENS/lupa.png"))); // NOI18N

        jlDescricaoVendaProd.setFont(new java.awt.Font("Times New Roman", 1, 12)); // NOI18N
        jlDescricaoVendaProd.setText("Descrição");

        jtfDescricaoProdVenda.setFont(new java.awt.Font("Times New Roman", 0, 12)); // NOI18N
        jtfDescricaoProdVenda.setEnabled(false);

        jbConsultaDescricaoVendaProd.setIcon(new javax.swing.ImageIcon(getClass().getResource("/IMAGENS/lupa.png"))); // NOI18N

        jlUnidMedidaVendaProd.setFont(new java.awt.Font("Times New Roman", 1, 12)); // NOI18N
        jlUnidMedidaVendaProd.setText("UN de medida");

        jlQuantidadeVendaProd.setFont(new java.awt.Font("Times New Roman", 1, 12)); // NOI18N
        jlQuantidadeVendaProd.setText("Quantidade");

        jtfQuantidadeVendaProd.setFont(new java.awt.Font("Times New Roman", 0, 12)); // NOI18N
        jtfQuantidadeVendaProd.setEnabled(false);

        jbNovoVendaProd.setFont(new java.awt.Font("Times New Roman", 1, 12)); // NOI18N
        jbNovoVendaProd.setIcon(new javax.swing.ImageIcon(getClass().getResource("/IMAGENS/novo.png"))); // NOI18N
        jbNovoVendaProd.setText("  Novo");
        jbNovoVendaProd.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbNovoVendaProdActionPerformed(evt);
            }
        });

        jbEditarVendaProd.setFont(new java.awt.Font("Times New Roman", 1, 12)); // NOI18N
        jbEditarVendaProd.setIcon(new javax.swing.ImageIcon(getClass().getResource("/IMAGENS/editar.png"))); // NOI18N
        jbEditarVendaProd.setText("  Editar");
        jbEditarVendaProd.setEnabled(false);

        jbIncluirVendaProd.setFont(new java.awt.Font("Times New Roman", 1, 12)); // NOI18N
        jbIncluirVendaProd.setIcon(new javax.swing.ImageIcon(getClass().getResource("/IMAGENS/salvar.png"))); // NOI18N
        jbIncluirVendaProd.setText("  Incluir");
        jbIncluirVendaProd.setEnabled(false);

        jlValorUnitVendaProd.setFont(new java.awt.Font("Times New Roman", 1, 12)); // NOI18N
        jlValorUnitVendaProd.setText("Valor Unitário");

        jtfValorUnitVendaProd.setFont(new java.awt.Font("Times New Roman", 0, 12)); // NOI18N
        jtfValorUnitVendaProd.setEnabled(false);

        jbExcluirVendaProd.setFont(new java.awt.Font("Times New Roman", 1, 12)); // NOI18N
        jbExcluirVendaProd.setIcon(new javax.swing.ImageIcon(getClass().getResource("/IMAGENS/excluir.png"))); // NOI18N
        jbExcluirVendaProd.setText("  Excluir");
        jbExcluirVendaProd.setEnabled(false);

        jtVendaProd.setFont(new java.awt.Font("Times New Roman", 0, 12)); // NOI18N
        jtVendaProd.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null}
            },
            new String [] {
                "CÓDIGO", "DESCRIÇÃO", "UN", "QTD", "VALOR UNIT", "VALOR TOTAL"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.Object.class
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }
        });
        jScrollPane16.setViewportView(jtVendaProd);

        jlValorTotalVendaProd.setFont(new java.awt.Font("Times New Roman", 1, 12)); // NOI18N
        jlValorTotalVendaProd.setText("Valor Total");

        jtfValorTotalVendaProd.setFont(new java.awt.Font("Times New Roman", 0, 12)); // NOI18N
        jtfValorTotalVendaProd.setEnabled(false);

        jbSalvarVenda.setFont(new java.awt.Font("Times New Roman", 1, 12)); // NOI18N
        jbSalvarVenda.setIcon(new javax.swing.ImageIcon(getClass().getResource("/IMAGENS/salvarCompra.png"))); // NOI18N
        jbSalvarVenda.setText("  Salvar");
        jbSalvarVenda.setEnabled(false);

        jbCancelarVenda.setFont(new java.awt.Font("Times New Roman", 1, 12)); // NOI18N
        jbCancelarVenda.setIcon(new javax.swing.ImageIcon(getClass().getResource("/IMAGENS/excluirCompra.png"))); // NOI18N
        jbCancelarVenda.setText("  Cancelar");

        jbImprimirVenda.setFont(new java.awt.Font("Times New Roman", 1, 12)); // NOI18N
        jbImprimirVenda.setIcon(new javax.swing.ImageIcon(getClass().getResource("/IMAGENS/imprimir.png"))); // NOI18N
        jbImprimirVenda.setText("  Imprimir");
        jbImprimirVenda.setEnabled(false);

        jlIdVenda.setFont(new java.awt.Font("Times New Roman", 1, 12)); // NOI18N
        jlIdVenda.setText("ID:");

        jlNumIdVenda.setFont(new java.awt.Font("Times New Roman", 1, 12)); // NOI18N
        jlNumIdVenda.setText("0");

        jpValorTotalVenda.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Valor Total da Venda", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Times New Roman", 1, 12))); // NOI18N

        jlValorTotalVenda.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        jlValorTotalVenda.setText("R$ ");

        jtfValorTotalVenda.setFont(new java.awt.Font("Times New Roman", 0, 12)); // NOI18N
        jtfValorTotalVenda.setEnabled(false);

        javax.swing.GroupLayout jpValorTotalVendaLayout = new javax.swing.GroupLayout(jpValorTotalVenda);
        jpValorTotalVenda.setLayout(jpValorTotalVendaLayout);
        jpValorTotalVendaLayout.setHorizontalGroup(
            jpValorTotalVendaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jpValorTotalVendaLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jlValorTotalVenda)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jtfValorTotalVenda)
                .addContainerGap())
        );
        jpValorTotalVendaLayout.setVerticalGroup(
            jpValorTotalVendaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jpValorTotalVendaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                .addComponent(jlValorTotalVenda, javax.swing.GroupLayout.DEFAULT_SIZE, 27, Short.MAX_VALUE)
                .addComponent(jtfValorTotalVenda, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        jlDataVenda.setFont(new java.awt.Font("Times New Roman", 1, 12)); // NOI18N
        jlDataVenda.setText("Data:");

        jtfDataVenda.setFont(new java.awt.Font("Times New Roman", 0, 12)); // NOI18N

        jtfUnidMedida.setEnabled(false);

        javax.swing.GroupLayout jpVendaLayout = new javax.swing.GroupLayout(jpVenda);
        jpVenda.setLayout(jpVendaLayout);
        jpVendaLayout.setHorizontalGroup(
            jpVendaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jpVendaLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jpVendaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jpVendaLayout.createSequentialGroup()
                        .addComponent(jlIdVenda)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jlNumIdVenda)
                        .addGap(27, 27, 27)
                        .addComponent(jlDataVenda)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jtfDataVenda, javax.swing.GroupLayout.PREFERRED_SIZE, 92, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(jpVendaLayout.createSequentialGroup()
                        .addGroup(jpVendaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jpVendaLayout.createSequentialGroup()
                                .addComponent(jpValorTotalVenda, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jbSalvarVenda)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jbCancelarVenda)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jbImprimirVenda))
                            .addGroup(jpVendaLayout.createSequentialGroup()
                                .addGroup(jpVendaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(jlUnidMedidaVendaProd, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(jtfUnidMedida))
                                .addGap(30, 30, 30)
                                .addGroup(jpVendaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jlQuantidadeVendaProd)
                                    .addComponent(jtfQuantidadeVendaProd, javax.swing.GroupLayout.PREFERRED_SIZE, 107, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(18, 18, 18)
                                .addGroup(jpVendaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(jpVendaLayout.createSequentialGroup()
                                        .addComponent(jlValorUnitVendaProd)
                                        .addGap(44, 44, 44))
                                    .addComponent(jtfValorUnitVendaProd))
                                .addGap(18, 18, 18)
                                .addGroup(jpVendaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jlValorTotalVendaProd)
                                    .addComponent(jtfValorTotalVendaProd)))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jpVendaLayout.createSequentialGroup()
                                .addGroup(jpVendaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jlCodigoVendaProd, javax.swing.GroupLayout.PREFERRED_SIZE, 79, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGroup(jpVendaLayout.createSequentialGroup()
                                        .addComponent(jtfCodigoVendaProd, javax.swing.GroupLayout.PREFERRED_SIZE, 107, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(jbConsultaCodigoVendaProd, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 53, Short.MAX_VALUE)
                                .addGroup(jpVendaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jlDescricaoVendaProd)
                                    .addGroup(jpVendaLayout.createSequentialGroup()
                                        .addComponent(jtfDescricaoProdVenda, javax.swing.GroupLayout.PREFERRED_SIZE, 367, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(jbConsultaDescricaoVendaProd, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE))))
                            .addGroup(jpVendaLayout.createSequentialGroup()
                                .addGap(28, 28, 28)
                                .addComponent(jbNovoVendaProd)
                                .addGap(26, 26, 26)
                                .addComponent(jbEditarVendaProd)
                                .addGap(27, 27, 27)
                                .addComponent(jbIncluirVendaProd)
                                .addGap(18, 18, 18)
                                .addComponent(jbExcluirVendaProd)
                                .addGap(0, 0, Short.MAX_VALUE))
                            .addComponent(jScrollPane16, javax.swing.GroupLayout.Alignment.TRAILING))
                        .addContainerGap())))
        );
        jpVendaLayout.setVerticalGroup(
            jpVendaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jpVendaLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jpVendaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jlIdVenda)
                    .addComponent(jlNumIdVenda)
                    .addComponent(jlDataVenda)
                    .addComponent(jtfDataVenda, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jpVendaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jlDescricaoVendaProd)
                    .addGroup(jpVendaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(jpVendaLayout.createSequentialGroup()
                            .addComponent(jlCodigoVendaProd)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                            .addComponent(jtfCodigoVendaProd, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addComponent(jtfDescricaoProdVenda, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jbConsultaCodigoVendaProd, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jbConsultaDescricaoVendaProd, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jpVendaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jpVendaLayout.createSequentialGroup()
                        .addComponent(jlValorUnitVendaProd)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jtfValorUnitVendaProd, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jpVendaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jpVendaLayout.createSequentialGroup()
                            .addComponent(jlQuantidadeVendaProd)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                            .addGroup(jpVendaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                .addComponent(jtfQuantidadeVendaProd, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(jtfUnidMedida, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addComponent(jlUnidMedidaVendaProd))
                    .addGroup(jpVendaLayout.createSequentialGroup()
                        .addComponent(jlValorTotalVendaProd)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jtfValorTotalVendaProd, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(18, 18, 18)
                .addGroup(jpVendaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jbNovoVendaProd)
                    .addComponent(jbEditarVendaProd)
                    .addComponent(jbIncluirVendaProd)
                    .addComponent(jbExcluirVendaProd))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jScrollPane16, javax.swing.GroupLayout.PREFERRED_SIZE, 191, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGroup(jpVendaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jpVendaLayout.createSequentialGroup()
                        .addGap(15, 15, 15)
                        .addGroup(jpVendaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jbSalvarVenda)
                            .addComponent(jbCancelarVenda)
                            .addComponent(jbImprimirVenda)))
                    .addGroup(jpVendaLayout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jpValorTotalVenda, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(69, 69, 69))
        );

        javax.swing.GroupLayout jpVendaFisicoLayout = new javax.swing.GroupLayout(jpVendaFisico);
        jpVendaFisico.setLayout(jpVendaFisicoLayout);
        jpVendaFisicoLayout.setHorizontalGroup(
            jpVendaFisicoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jpVendaFisicoLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jpVendaFisicoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jpClienteFisico, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jpVenda, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(29, Short.MAX_VALUE))
        );
        jpVendaFisicoLayout.setVerticalGroup(
            jpVendaFisicoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jpVendaFisicoLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jpClienteFisico, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jpVenda, javax.swing.GroupLayout.PREFERRED_SIZE, 530, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(23, Short.MAX_VALUE))
        );

        jScrollPane1.setViewportView(jpVendaFisico);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jScrollPane1)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jScrollPane1)
                .addContainerGap())
        );

        setBounds(0, 0, 700, 725);
    }// </editor-fold>//GEN-END:initComponents

    private void jbNovoVendaProdActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbNovoVendaProdActionPerformed
        try {
            if(preencherObjetoItens()){
                if(DAO.incluirItens(obj)){
                    JOptionPane.showMessageDialog(this, "Produto registrado!",
                            "Meu sistema", JOptionPane.INFORMATION_MESSAGE);
                    //Salva no banco de dados.
                    limparCamposProduto(); //Limpa os campos.
                }
            }
        } catch (Exception erro) {
            JOptionPane.showMessageDialog(this, "Erro ao salvar:"+erro.getMessage(),"Sistema", JOptionPane.ERROR_MESSAGE);
        }
    }//GEN-LAST:event_jbNovoVendaProdActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane16;
    private javax.swing.JButton jbCancelarVenda;
    private javax.swing.JButton jbConsultaCNPJCpfCliente;
    private javax.swing.JButton jbConsultaCodigoVendaProd;
    private javax.swing.JButton jbConsultaDescricaoVendaProd;
    private javax.swing.JButton jbConsultaRazaoSocialNomeCliente;
    private javax.swing.JButton jbEditarVendaProd;
    private javax.swing.JButton jbExcluirVendaProd;
    private javax.swing.JButton jbImprimirVenda;
    private javax.swing.JButton jbIncluirVendaProd;
    private javax.swing.JButton jbNovoVendaProd;
    private javax.swing.JButton jbSalvarVenda;
    private javax.swing.JLabel jlCnpjCpfCliente;
    private javax.swing.JLabel jlCodigoVendaProd;
    private javax.swing.JLabel jlDataVenda;
    private javax.swing.JLabel jlDescricaoVendaProd;
    private javax.swing.JLabel jlIdVenda;
    private javax.swing.JLabel jlNumIdVenda;
    private javax.swing.JLabel jlQuantidadeVendaProd;
    private javax.swing.JLabel jlRazaoSocialNomeCliente;
    private javax.swing.JLabel jlUnidMedidaVendaProd;
    private javax.swing.JLabel jlValorTotalVenda;
    private javax.swing.JLabel jlValorTotalVendaProd;
    private javax.swing.JLabel jlValorUnitVendaProd;
    private javax.swing.JPanel jpClienteFisico;
    private javax.swing.JPanel jpValorTotalVenda;
    private javax.swing.JPanel jpVenda;
    private javax.swing.JPanel jpVendaFisico;
    private javax.swing.JTable jtVendaProd;
    private javax.swing.JTextField jtfCnpjCpfCliente;
    private javax.swing.JTextField jtfCodigoVendaProd;
    private javax.swing.JTextField jtfDataVenda;
    private javax.swing.JTextField jtfDescricaoProdVenda;
    private javax.swing.JTextField jtfQuantidadeVendaProd;
    private javax.swing.JTextField jtfRazaoSocialNomeCliente;
    private javax.swing.JTextField jtfUnidMedida;
    private javax.swing.JTextField jtfValorTotalVenda;
    private javax.swing.JTextField jtfValorTotalVendaProd;
    private javax.swing.JTextField jtfValorUnitVendaProd;
    // End of variables declaration//GEN-END:variables

private void limparCamposProduto(){
    jtfDataVenda.setText("");
    jtfCodigoVendaProd.setText("");
    jtfDescricaoProdVenda.setText("");
    jtfUnidMedida.setText("");
    jtfQuantidadeVendaProd.setText("");
    jtfValorUnitVendaProd.setText("");
    jtfValorTotalVenda.setText("");
}
private boolean preencherObjeto() throws Exception{
    obj.setCnpjCpf(jtfCnpjCpfCliente.getText());
    obj.setRazaoSocialNome(jtfRazaoSocialNomeCliente.getText());
    obj.setData(jtfDataVenda.getText());
    return true;
}

private boolean preencherObjetoItens() throws Exception{
    obj.setCodVenda(Integer.parseInt(jtfCodigoVendaProd.getText()));
    obj.setDescricao(jtfDescricaoProdVenda.getText());
    obj.setUnMedida(jtfUnidMedida.getText());
    obj.setQuantidade(Integer.parseInt(jtfQuantidadeVendaProd.getText()));
    obj.setValorUnit(Integer.parseInt(jtfValorUnitVendaProd.getText()));
    obj.setValorTotal(Integer.parseInt(jtfValorTotalVendaProd.getText()));
    obj.setValorTotal(Integer.parseInt(jtfValorTotalVenda.getText()));
    return true;
}

}
