/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package VIEW;

/**
 *
 * @author Roberto Junior Akira
 */
public class JIFNovoCadastroClienteJuridico extends javax.swing.JInternalFrame {

    /**
     * Creates new form JIFCadastroClienteJuridico
     */
    public JIFNovoCadastroClienteJuridico() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jpCadatroClienteFisico = new javax.swing.JPanel();
        jlCodigoClienteJuridico = new javax.swing.JLabel();
        jlCodigoNumClienteJuridico = new javax.swing.JLabel();
        jpDadosEmpresarialClienteJuridico = new javax.swing.JPanel();
        jlRazaoSocialClienteJuridico = new javax.swing.JLabel();
        jtfRazaoSocialClienteJuridico = new javax.swing.JTextField();
        jlCnpjClienteJuridico = new javax.swing.JLabel();
        jtfCnpjClienteJuridico = new javax.swing.JTextField();
        jlInscEstadualClienteJuridico = new javax.swing.JLabel();
        jtfInscEstadualClienteJuridico = new javax.swing.JTextField();
        jpContatoClienteJuridico = new javax.swing.JPanel();
        jpEnderecoClienteJuridico = new javax.swing.JPanel();
        jlLogadouroClienteJuridico = new javax.swing.JLabel();
        jtfLogadouroClienteJuridico = new javax.swing.JTextField();
        jlNumeroEndClienteJuridico = new javax.swing.JLabel();
        jtfNumeroEndClienteJuridico = new javax.swing.JTextField();
        jlComplementoEndClienteJuridico = new javax.swing.JLabel();
        jtfComplementoEndClienteJuridico = new javax.swing.JTextField();
        jlBairroEndClienteJuridico = new javax.swing.JLabel();
        jtfBairroEndClienteJuridico = new javax.swing.JTextField();
        jlCepEndClienteJuridico = new javax.swing.JLabel();
        jtfCepEndClienteJuridico = new javax.swing.JTextField();
        jlCidadeEndClienteJuridico = new javax.swing.JLabel();
        jtfCidadeEndClienteJuridico = new javax.swing.JTextField();
        jlEstadoEndClienteJuridico = new javax.swing.JLabel();
        jtfEstadoEndClienteJuridico = new javax.swing.JTextField();
        jpEmailClienteJuridico = new javax.swing.JPanel();
        jtfEmailClienteJuridico = new javax.swing.JTextField();
        jpTelefoneClienteJuridico = new javax.swing.JPanel();
        jtfTelefoneClienteJuridico = new javax.swing.JTextField();
        jbSalvarClienteJuridico = new javax.swing.JButton();
        jbCancelarClienteJuridico1 = new javax.swing.JButton();

        setClosable(true);
        setIconifiable(true);

        jpCadatroClienteFisico.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Cliente Juridico", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Times New Roman", 1, 12))); // NOI18N

        jlCodigoClienteJuridico.setFont(new java.awt.Font("Times New Roman", 1, 12)); // NOI18N
        jlCodigoClienteJuridico.setText("Código");

        jlCodigoNumClienteJuridico.setFont(new java.awt.Font("Times New Roman", 1, 12)); // NOI18N
        jlCodigoNumClienteJuridico.setText("0");

        jpDadosEmpresarialClienteJuridico.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Dados Empresarial", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Times New Roman", 1, 12))); // NOI18N

        jlRazaoSocialClienteJuridico.setFont(new java.awt.Font("Times New Roman", 1, 12)); // NOI18N
        jlRazaoSocialClienteJuridico.setText("Razão Social");

        jtfRazaoSocialClienteJuridico.setFont(new java.awt.Font("Times New Roman", 0, 12)); // NOI18N

        jlCnpjClienteJuridico.setFont(new java.awt.Font("Times New Roman", 1, 12)); // NOI18N
        jlCnpjClienteJuridico.setText("CNPJ");

        jtfCnpjClienteJuridico.setFont(new java.awt.Font("Times New Roman", 0, 12)); // NOI18N

        jlInscEstadualClienteJuridico.setFont(new java.awt.Font("Times New Roman", 1, 12)); // NOI18N
        jlInscEstadualClienteJuridico.setText("Inscrição Estadual");

        jtfInscEstadualClienteJuridico.setFont(new java.awt.Font("Times New Roman", 0, 12)); // NOI18N

        javax.swing.GroupLayout jpDadosEmpresarialClienteJuridicoLayout = new javax.swing.GroupLayout(jpDadosEmpresarialClienteJuridico);
        jpDadosEmpresarialClienteJuridico.setLayout(jpDadosEmpresarialClienteJuridicoLayout);
        jpDadosEmpresarialClienteJuridicoLayout.setHorizontalGroup(
            jpDadosEmpresarialClienteJuridicoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jpDadosEmpresarialClienteJuridicoLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jpDadosEmpresarialClienteJuridicoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jpDadosEmpresarialClienteJuridicoLayout.createSequentialGroup()
                        .addComponent(jlRazaoSocialClienteJuridico)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(jpDadosEmpresarialClienteJuridicoLayout.createSequentialGroup()
                        .addGroup(jpDadosEmpresarialClienteJuridicoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jlCnpjClienteJuridico)
                            .addComponent(jtfCnpjClienteJuridico, javax.swing.GroupLayout.PREFERRED_SIZE, 285, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(jpDadosEmpresarialClienteJuridicoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jpDadosEmpresarialClienteJuridicoLayout.createSequentialGroup()
                                .addComponent(jlInscEstadualClienteJuridico)
                                .addGap(192, 192, 192))
                            .addComponent(jtfInscEstadualClienteJuridico)))
                    .addComponent(jtfRazaoSocialClienteJuridico))
                .addGap(30, 30, 30))
        );
        jpDadosEmpresarialClienteJuridicoLayout.setVerticalGroup(
            jpDadosEmpresarialClienteJuridicoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jpDadosEmpresarialClienteJuridicoLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jlRazaoSocialClienteJuridico)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jtfRazaoSocialClienteJuridico, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jpDadosEmpresarialClienteJuridicoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jpDadosEmpresarialClienteJuridicoLayout.createSequentialGroup()
                        .addComponent(jlCnpjClienteJuridico)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jtfCnpjClienteJuridico, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jpDadosEmpresarialClienteJuridicoLayout.createSequentialGroup()
                        .addComponent(jlInscEstadualClienteJuridico)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jtfInscEstadualClienteJuridico, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jpContatoClienteJuridico.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Contato", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Times New Roman", 1, 12))); // NOI18N

        jpEnderecoClienteJuridico.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Endereço", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Times New Roman", 1, 12))); // NOI18N

        jlLogadouroClienteJuridico.setFont(new java.awt.Font("Times New Roman", 1, 12)); // NOI18N
        jlLogadouroClienteJuridico.setText("Logadouro");

        jtfLogadouroClienteJuridico.setFont(new java.awt.Font("Times New Roman", 0, 12)); // NOI18N

        jlNumeroEndClienteJuridico.setFont(new java.awt.Font("Times New Roman", 1, 12)); // NOI18N
        jlNumeroEndClienteJuridico.setText("Número");

        jtfNumeroEndClienteJuridico.setFont(new java.awt.Font("Times New Roman", 0, 12)); // NOI18N

        jlComplementoEndClienteJuridico.setFont(new java.awt.Font("Times New Roman", 1, 12)); // NOI18N
        jlComplementoEndClienteJuridico.setText("Complemento");

        jtfComplementoEndClienteJuridico.setFont(new java.awt.Font("Times New Roman", 0, 12)); // NOI18N

        jlBairroEndClienteJuridico.setFont(new java.awt.Font("Times New Roman", 1, 12)); // NOI18N
        jlBairroEndClienteJuridico.setText("Bairro");

        jtfBairroEndClienteJuridico.setFont(new java.awt.Font("Times New Roman", 0, 12)); // NOI18N

        jlCepEndClienteJuridico.setFont(new java.awt.Font("Times New Roman", 1, 12)); // NOI18N
        jlCepEndClienteJuridico.setText("CEP");

        jtfCepEndClienteJuridico.setFont(new java.awt.Font("Times New Roman", 0, 12)); // NOI18N

        jlCidadeEndClienteJuridico.setFont(new java.awt.Font("Times New Roman", 1, 12)); // NOI18N
        jlCidadeEndClienteJuridico.setText("Cidade");

        jtfCidadeEndClienteJuridico.setFont(new java.awt.Font("Times New Roman", 0, 12)); // NOI18N

        jlEstadoEndClienteJuridico.setFont(new java.awt.Font("Times New Roman", 1, 12)); // NOI18N
        jlEstadoEndClienteJuridico.setText("Estado");

        jtfEstadoEndClienteJuridico.setFont(new java.awt.Font("Times New Roman", 0, 12)); // NOI18N

        javax.swing.GroupLayout jpEnderecoClienteJuridicoLayout = new javax.swing.GroupLayout(jpEnderecoClienteJuridico);
        jpEnderecoClienteJuridico.setLayout(jpEnderecoClienteJuridicoLayout);
        jpEnderecoClienteJuridicoLayout.setHorizontalGroup(
            jpEnderecoClienteJuridicoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jpEnderecoClienteJuridicoLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jpEnderecoClienteJuridicoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jpEnderecoClienteJuridicoLayout.createSequentialGroup()
                        .addGroup(jpEnderecoClienteJuridicoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jlBairroEndClienteJuridico, javax.swing.GroupLayout.PREFERRED_SIZE, 79, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jtfBairroEndClienteJuridico, javax.swing.GroupLayout.PREFERRED_SIZE, 166, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(jpEnderecoClienteJuridicoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jlCepEndClienteJuridico, javax.swing.GroupLayout.PREFERRED_SIZE, 79, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jtfCepEndClienteJuridico, javax.swing.GroupLayout.PREFERRED_SIZE, 128, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(jpEnderecoClienteJuridicoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jpEnderecoClienteJuridicoLayout.createSequentialGroup()
                                .addComponent(jlCidadeEndClienteJuridico, javax.swing.GroupLayout.PREFERRED_SIZE, 79, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(0, 80, Short.MAX_VALUE))
                            .addComponent(jtfCidadeEndClienteJuridico))
                        .addGap(18, 18, 18)
                        .addGroup(jpEnderecoClienteJuridicoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jlEstadoEndClienteJuridico, javax.swing.GroupLayout.PREFERRED_SIZE, 79, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jtfEstadoEndClienteJuridico, javax.swing.GroupLayout.PREFERRED_SIZE, 107, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(jpEnderecoClienteJuridicoLayout.createSequentialGroup()
                        .addGroup(jpEnderecoClienteJuridicoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jpEnderecoClienteJuridicoLayout.createSequentialGroup()
                                .addComponent(jlLogadouroClienteJuridico, javax.swing.GroupLayout.PREFERRED_SIZE, 79, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(0, 0, Short.MAX_VALUE))
                            .addComponent(jtfLogadouroClienteJuridico))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(jpEnderecoClienteJuridicoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jlNumeroEndClienteJuridico, javax.swing.GroupLayout.PREFERRED_SIZE, 79, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jtfNumeroEndClienteJuridico, javax.swing.GroupLayout.PREFERRED_SIZE, 107, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(jpEnderecoClienteJuridicoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jlComplementoEndClienteJuridico, javax.swing.GroupLayout.PREFERRED_SIZE, 79, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jtfComplementoEndClienteJuridico, javax.swing.GroupLayout.PREFERRED_SIZE, 107, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addContainerGap())
        );
        jpEnderecoClienteJuridicoLayout.setVerticalGroup(
            jpEnderecoClienteJuridicoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jpEnderecoClienteJuridicoLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jpEnderecoClienteJuridicoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jpEnderecoClienteJuridicoLayout.createSequentialGroup()
                        .addComponent(jlLogadouroClienteJuridico)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jtfLogadouroClienteJuridico, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jpEnderecoClienteJuridicoLayout.createSequentialGroup()
                        .addComponent(jlNumeroEndClienteJuridico)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jtfNumeroEndClienteJuridico, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jpEnderecoClienteJuridicoLayout.createSequentialGroup()
                        .addComponent(jlComplementoEndClienteJuridico)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jtfComplementoEndClienteJuridico, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jpEnderecoClienteJuridicoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jpEnderecoClienteJuridicoLayout.createSequentialGroup()
                        .addComponent(jlBairroEndClienteJuridico)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jtfBairroEndClienteJuridico, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jpEnderecoClienteJuridicoLayout.createSequentialGroup()
                        .addComponent(jlCepEndClienteJuridico)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jtfCepEndClienteJuridico, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jpEnderecoClienteJuridicoLayout.createSequentialGroup()
                        .addComponent(jlCidadeEndClienteJuridico)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jtfCidadeEndClienteJuridico, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jpEnderecoClienteJuridicoLayout.createSequentialGroup()
                        .addComponent(jlEstadoEndClienteJuridico)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jtfEstadoEndClienteJuridico, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jpEmailClienteJuridico.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "E-mail", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Times New Roman", 1, 12))); // NOI18N

        jtfEmailClienteJuridico.setFont(new java.awt.Font("Times New Roman", 0, 12)); // NOI18N

        javax.swing.GroupLayout jpEmailClienteJuridicoLayout = new javax.swing.GroupLayout(jpEmailClienteJuridico);
        jpEmailClienteJuridico.setLayout(jpEmailClienteJuridicoLayout);
        jpEmailClienteJuridicoLayout.setHorizontalGroup(
            jpEmailClienteJuridicoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jpEmailClienteJuridicoLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jtfEmailClienteJuridico)
                .addContainerGap())
        );
        jpEmailClienteJuridicoLayout.setVerticalGroup(
            jpEmailClienteJuridicoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jtfEmailClienteJuridico, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        jpTelefoneClienteJuridico.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Telefone", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Times New Roman", 1, 12))); // NOI18N

        jtfTelefoneClienteJuridico.setFont(new java.awt.Font("Times New Roman", 0, 12)); // NOI18N

        javax.swing.GroupLayout jpTelefoneClienteJuridicoLayout = new javax.swing.GroupLayout(jpTelefoneClienteJuridico);
        jpTelefoneClienteJuridico.setLayout(jpTelefoneClienteJuridicoLayout);
        jpTelefoneClienteJuridicoLayout.setHorizontalGroup(
            jpTelefoneClienteJuridicoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jpTelefoneClienteJuridicoLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jtfTelefoneClienteJuridico, javax.swing.GroupLayout.DEFAULT_SIZE, 261, Short.MAX_VALUE)
                .addContainerGap())
        );
        jpTelefoneClienteJuridicoLayout.setVerticalGroup(
            jpTelefoneClienteJuridicoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jtfTelefoneClienteJuridico, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        javax.swing.GroupLayout jpContatoClienteJuridicoLayout = new javax.swing.GroupLayout(jpContatoClienteJuridico);
        jpContatoClienteJuridico.setLayout(jpContatoClienteJuridicoLayout);
        jpContatoClienteJuridicoLayout.setHorizontalGroup(
            jpContatoClienteJuridicoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jpContatoClienteJuridicoLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jpContatoClienteJuridicoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jpEnderecoClienteJuridico, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(jpContatoClienteJuridicoLayout.createSequentialGroup()
                        .addComponent(jpEmailClienteJuridico, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jpTelefoneClienteJuridico, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap())
        );
        jpContatoClienteJuridicoLayout.setVerticalGroup(
            jpContatoClienteJuridicoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jpContatoClienteJuridicoLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jpEnderecoClienteJuridico, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jpContatoClienteJuridicoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jpEmailClienteJuridico, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jpTelefoneClienteJuridico, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jbSalvarClienteJuridico.setFont(new java.awt.Font("Times New Roman", 1, 12)); // NOI18N
        jbSalvarClienteJuridico.setIcon(new javax.swing.ImageIcon(getClass().getResource("/IMAGENS/1salvar.png"))); // NOI18N
        jbSalvarClienteJuridico.setText("  Salvar");
        jbSalvarClienteJuridico.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbSalvarClienteJuridicoActionPerformed(evt);
            }
        });

        jbCancelarClienteJuridico1.setFont(new java.awt.Font("Times New Roman", 1, 12)); // NOI18N
        jbCancelarClienteJuridico1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/IMAGENS/1excluir.png"))); // NOI18N
        jbCancelarClienteJuridico1.setText("  Cancelar");
        jbCancelarClienteJuridico1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbCancelarClienteJuridico1ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jpCadatroClienteFisicoLayout = new javax.swing.GroupLayout(jpCadatroClienteFisico);
        jpCadatroClienteFisico.setLayout(jpCadatroClienteFisicoLayout);
        jpCadatroClienteFisicoLayout.setHorizontalGroup(
            jpCadatroClienteFisicoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jpCadatroClienteFisicoLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jpCadatroClienteFisicoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jpCadatroClienteFisicoLayout.createSequentialGroup()
                        .addComponent(jbSalvarClienteJuridico, javax.swing.GroupLayout.PREFERRED_SIZE, 123, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jbCancelarClienteJuridico1))
                    .addGroup(jpCadatroClienteFisicoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                        .addComponent(jpContatoClienteJuridico, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(jpCadatroClienteFisicoLayout.createSequentialGroup()
                            .addComponent(jlCodigoClienteJuridico)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                            .addComponent(jlCodigoNumClienteJuridico))
                        .addComponent(jpDadosEmpresarialClienteJuridico, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                .addGap(0, 20, Short.MAX_VALUE))
        );
        jpCadatroClienteFisicoLayout.setVerticalGroup(
            jpCadatroClienteFisicoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jpCadatroClienteFisicoLayout.createSequentialGroup()
                .addGap(7, 7, 7)
                .addGroup(jpCadatroClienteFisicoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jlCodigoClienteJuridico)
                    .addComponent(jlCodigoNumClienteJuridico))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jpDadosEmpresarialClienteJuridico, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jpContatoClienteJuridico, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jpCadatroClienteFisicoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jbCancelarClienteJuridico1)
                    .addComponent(jbSalvarClienteJuridico))
                .addContainerGap(13, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jpCadatroClienteFisico, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jpCadatroClienteFisico, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jbSalvarClienteJuridicoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbSalvarClienteJuridicoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jbSalvarClienteJuridicoActionPerformed

    private void jbCancelarClienteJuridico1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbCancelarClienteJuridico1ActionPerformed
        dispose();
    }//GEN-LAST:event_jbCancelarClienteJuridico1ActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jbCancelarClienteJuridico1;
    private javax.swing.JButton jbSalvarClienteJuridico;
    private javax.swing.JLabel jlBairroEndClienteJuridico;
    private javax.swing.JLabel jlCepEndClienteJuridico;
    private javax.swing.JLabel jlCidadeEndClienteJuridico;
    private javax.swing.JLabel jlCnpjClienteJuridico;
    private javax.swing.JLabel jlCodigoClienteJuridico;
    private javax.swing.JLabel jlCodigoNumClienteJuridico;
    private javax.swing.JLabel jlComplementoEndClienteJuridico;
    private javax.swing.JLabel jlEstadoEndClienteJuridico;
    private javax.swing.JLabel jlInscEstadualClienteJuridico;
    private javax.swing.JLabel jlLogadouroClienteJuridico;
    private javax.swing.JLabel jlNumeroEndClienteJuridico;
    private javax.swing.JLabel jlRazaoSocialClienteJuridico;
    private javax.swing.JPanel jpCadatroClienteFisico;
    private javax.swing.JPanel jpContatoClienteJuridico;
    private javax.swing.JPanel jpDadosEmpresarialClienteJuridico;
    private javax.swing.JPanel jpEmailClienteJuridico;
    private javax.swing.JPanel jpEnderecoClienteJuridico;
    private javax.swing.JPanel jpTelefoneClienteJuridico;
    private javax.swing.JTextField jtfBairroEndClienteJuridico;
    private javax.swing.JTextField jtfCepEndClienteJuridico;
    private javax.swing.JTextField jtfCidadeEndClienteJuridico;
    private javax.swing.JTextField jtfCnpjClienteJuridico;
    private javax.swing.JTextField jtfComplementoEndClienteJuridico;
    private javax.swing.JTextField jtfEmailClienteJuridico;
    private javax.swing.JTextField jtfEstadoEndClienteJuridico;
    private javax.swing.JTextField jtfInscEstadualClienteJuridico;
    private javax.swing.JTextField jtfLogadouroClienteJuridico;
    private javax.swing.JTextField jtfNumeroEndClienteJuridico;
    private javax.swing.JTextField jtfRazaoSocialClienteJuridico;
    private javax.swing.JTextField jtfTelefoneClienteJuridico;
    // End of variables declaration//GEN-END:variables
}
