/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package VIEW;

/**
 *
 * @author Roberto Junior Akira
 */
public class JIFNovoCadastroFornecedor extends javax.swing.JInternalFrame {

    /**
     * Creates new form JIFCadastroFornecedor
     */
    public JIFNovoCadastroFornecedor() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jpCadatroFornecedor = new javax.swing.JPanel();
        jlCodigoFornecedor = new javax.swing.JLabel();
        jlCodigoNumFornecedor = new javax.swing.JLabel();
        jpDadosFornecedor = new javax.swing.JPanel();
        jlRazaoSocialFornecedor = new javax.swing.JLabel();
        jtfRazaoSocialFornecedor = new javax.swing.JTextField();
        jlCnpjFornecedor = new javax.swing.JLabel();
        jtfCnpjFornecedor = new javax.swing.JTextField();
        jlInscEstadualFornecedor = new javax.swing.JLabel();
        jtfInscEstadualFornecedor = new javax.swing.JTextField();
        jpContatoFornecedor = new javax.swing.JPanel();
        jpEnderecoFornecedor = new javax.swing.JPanel();
        jlLogadouroFornecedor = new javax.swing.JLabel();
        jtfLogadouroFornecedor = new javax.swing.JTextField();
        jlNumeroEndFornecedor = new javax.swing.JLabel();
        jtfNumeroEndFornecedor = new javax.swing.JTextField();
        jlComplementoEndFornecedor = new javax.swing.JLabel();
        jtfComplementoEndFornecedor = new javax.swing.JTextField();
        jlBairroEndFornecedor = new javax.swing.JLabel();
        jtfBairroEndFornecedor = new javax.swing.JTextField();
        jlCepEndFornecedor = new javax.swing.JLabel();
        jtfCepEndFornecedor = new javax.swing.JTextField();
        jlCidadeEndFornecedor = new javax.swing.JLabel();
        jtfCidadeEndFornecedor = new javax.swing.JTextField();
        jlEstadoEndFornecedor = new javax.swing.JLabel();
        jtfEstadoEndFornecedor = new javax.swing.JTextField();
        jpEmailFornecedor = new javax.swing.JPanel();
        jtfEmailFornecedor = new javax.swing.JTextField();
        jpTelefoneFornecedor = new javax.swing.JPanel();
        jtfTelefoneFornecedor = new javax.swing.JTextField();
        jbSalvarFornecedor = new javax.swing.JButton();
        jbCancelarFornecedor1 = new javax.swing.JButton();

        setClosable(true);
        setIconifiable(true);

        jpCadatroFornecedor.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Fornecedor", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Times New Roman", 1, 12))); // NOI18N

        jlCodigoFornecedor.setFont(new java.awt.Font("Times New Roman", 1, 12)); // NOI18N
        jlCodigoFornecedor.setText("Código");

        jlCodigoNumFornecedor.setFont(new java.awt.Font("Times New Roman", 1, 12)); // NOI18N
        jlCodigoNumFornecedor.setText("0");

        jpDadosFornecedor.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Dados Fornecedor", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Times New Roman", 1, 12))); // NOI18N

        jlRazaoSocialFornecedor.setFont(new java.awt.Font("Times New Roman", 1, 12)); // NOI18N
        jlRazaoSocialFornecedor.setText("Razão Social");

        jtfRazaoSocialFornecedor.setFont(new java.awt.Font("Times New Roman", 0, 12)); // NOI18N

        jlCnpjFornecedor.setFont(new java.awt.Font("Times New Roman", 1, 12)); // NOI18N
        jlCnpjFornecedor.setText("CNPJ");

        jtfCnpjFornecedor.setFont(new java.awt.Font("Times New Roman", 0, 12)); // NOI18N

        jlInscEstadualFornecedor.setFont(new java.awt.Font("Times New Roman", 1, 12)); // NOI18N
        jlInscEstadualFornecedor.setText("Inscrição Estadual");

        jtfInscEstadualFornecedor.setFont(new java.awt.Font("Times New Roman", 0, 12)); // NOI18N

        javax.swing.GroupLayout jpDadosFornecedorLayout = new javax.swing.GroupLayout(jpDadosFornecedor);
        jpDadosFornecedor.setLayout(jpDadosFornecedorLayout);
        jpDadosFornecedorLayout.setHorizontalGroup(
            jpDadosFornecedorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jpDadosFornecedorLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jpDadosFornecedorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jpDadosFornecedorLayout.createSequentialGroup()
                        .addComponent(jlRazaoSocialFornecedor)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(jpDadosFornecedorLayout.createSequentialGroup()
                        .addGroup(jpDadosFornecedorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jlCnpjFornecedor)
                            .addComponent(jtfCnpjFornecedor, javax.swing.GroupLayout.PREFERRED_SIZE, 285, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(jpDadosFornecedorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jpDadosFornecedorLayout.createSequentialGroup()
                                .addComponent(jlInscEstadualFornecedor)
                                .addGap(192, 192, 192))
                            .addComponent(jtfInscEstadualFornecedor)))
                    .addComponent(jtfRazaoSocialFornecedor))
                .addGap(30, 30, 30))
        );
        jpDadosFornecedorLayout.setVerticalGroup(
            jpDadosFornecedorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jpDadosFornecedorLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jlRazaoSocialFornecedor)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jtfRazaoSocialFornecedor, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jpDadosFornecedorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jpDadosFornecedorLayout.createSequentialGroup()
                        .addComponent(jlCnpjFornecedor)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jtfCnpjFornecedor, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jpDadosFornecedorLayout.createSequentialGroup()
                        .addComponent(jlInscEstadualFornecedor)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jtfInscEstadualFornecedor, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jpContatoFornecedor.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Contato", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Times New Roman", 1, 12))); // NOI18N

        jpEnderecoFornecedor.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Endereço", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Times New Roman", 1, 12))); // NOI18N

        jlLogadouroFornecedor.setFont(new java.awt.Font("Times New Roman", 1, 12)); // NOI18N
        jlLogadouroFornecedor.setText("Logadouro");

        jtfLogadouroFornecedor.setFont(new java.awt.Font("Times New Roman", 0, 12)); // NOI18N

        jlNumeroEndFornecedor.setFont(new java.awt.Font("Times New Roman", 1, 12)); // NOI18N
        jlNumeroEndFornecedor.setText("Número");

        jtfNumeroEndFornecedor.setFont(new java.awt.Font("Times New Roman", 0, 12)); // NOI18N

        jlComplementoEndFornecedor.setFont(new java.awt.Font("Times New Roman", 1, 12)); // NOI18N
        jlComplementoEndFornecedor.setText("Complemento");

        jtfComplementoEndFornecedor.setFont(new java.awt.Font("Times New Roman", 0, 12)); // NOI18N

        jlBairroEndFornecedor.setFont(new java.awt.Font("Times New Roman", 1, 12)); // NOI18N
        jlBairroEndFornecedor.setText("Bairro");

        jtfBairroEndFornecedor.setFont(new java.awt.Font("Times New Roman", 0, 12)); // NOI18N

        jlCepEndFornecedor.setFont(new java.awt.Font("Times New Roman", 1, 12)); // NOI18N
        jlCepEndFornecedor.setText("CEP");

        jtfCepEndFornecedor.setFont(new java.awt.Font("Times New Roman", 0, 12)); // NOI18N

        jlCidadeEndFornecedor.setFont(new java.awt.Font("Times New Roman", 1, 12)); // NOI18N
        jlCidadeEndFornecedor.setText("Cidade");

        jtfCidadeEndFornecedor.setFont(new java.awt.Font("Times New Roman", 0, 12)); // NOI18N

        jlEstadoEndFornecedor.setFont(new java.awt.Font("Times New Roman", 1, 12)); // NOI18N
        jlEstadoEndFornecedor.setText("Estado");

        jtfEstadoEndFornecedor.setFont(new java.awt.Font("Times New Roman", 0, 12)); // NOI18N

        javax.swing.GroupLayout jpEnderecoFornecedorLayout = new javax.swing.GroupLayout(jpEnderecoFornecedor);
        jpEnderecoFornecedor.setLayout(jpEnderecoFornecedorLayout);
        jpEnderecoFornecedorLayout.setHorizontalGroup(
            jpEnderecoFornecedorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jpEnderecoFornecedorLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jpEnderecoFornecedorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jpEnderecoFornecedorLayout.createSequentialGroup()
                        .addGroup(jpEnderecoFornecedorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jlBairroEndFornecedor, javax.swing.GroupLayout.PREFERRED_SIZE, 79, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jtfBairroEndFornecedor, javax.swing.GroupLayout.PREFERRED_SIZE, 166, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(jpEnderecoFornecedorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jlCepEndFornecedor, javax.swing.GroupLayout.PREFERRED_SIZE, 79, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jtfCepEndFornecedor, javax.swing.GroupLayout.PREFERRED_SIZE, 128, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(jpEnderecoFornecedorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jpEnderecoFornecedorLayout.createSequentialGroup()
                                .addComponent(jlCidadeEndFornecedor, javax.swing.GroupLayout.PREFERRED_SIZE, 79, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(0, 80, Short.MAX_VALUE))
                            .addComponent(jtfCidadeEndFornecedor))
                        .addGap(18, 18, 18)
                        .addGroup(jpEnderecoFornecedorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jlEstadoEndFornecedor, javax.swing.GroupLayout.PREFERRED_SIZE, 79, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jtfEstadoEndFornecedor, javax.swing.GroupLayout.PREFERRED_SIZE, 107, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(jpEnderecoFornecedorLayout.createSequentialGroup()
                        .addGroup(jpEnderecoFornecedorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jpEnderecoFornecedorLayout.createSequentialGroup()
                                .addComponent(jlLogadouroFornecedor, javax.swing.GroupLayout.PREFERRED_SIZE, 79, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(0, 0, Short.MAX_VALUE))
                            .addComponent(jtfLogadouroFornecedor))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(jpEnderecoFornecedorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jlNumeroEndFornecedor, javax.swing.GroupLayout.PREFERRED_SIZE, 79, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jtfNumeroEndFornecedor, javax.swing.GroupLayout.PREFERRED_SIZE, 107, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(jpEnderecoFornecedorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jlComplementoEndFornecedor, javax.swing.GroupLayout.PREFERRED_SIZE, 79, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jtfComplementoEndFornecedor, javax.swing.GroupLayout.PREFERRED_SIZE, 107, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addContainerGap())
        );
        jpEnderecoFornecedorLayout.setVerticalGroup(
            jpEnderecoFornecedorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jpEnderecoFornecedorLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jpEnderecoFornecedorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jpEnderecoFornecedorLayout.createSequentialGroup()
                        .addComponent(jlLogadouroFornecedor)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jtfLogadouroFornecedor, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jpEnderecoFornecedorLayout.createSequentialGroup()
                        .addComponent(jlNumeroEndFornecedor)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jtfNumeroEndFornecedor, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jpEnderecoFornecedorLayout.createSequentialGroup()
                        .addComponent(jlComplementoEndFornecedor)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jtfComplementoEndFornecedor, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jpEnderecoFornecedorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jpEnderecoFornecedorLayout.createSequentialGroup()
                        .addComponent(jlBairroEndFornecedor)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jtfBairroEndFornecedor, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jpEnderecoFornecedorLayout.createSequentialGroup()
                        .addComponent(jlCepEndFornecedor)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jtfCepEndFornecedor, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jpEnderecoFornecedorLayout.createSequentialGroup()
                        .addComponent(jlCidadeEndFornecedor)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jtfCidadeEndFornecedor, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jpEnderecoFornecedorLayout.createSequentialGroup()
                        .addComponent(jlEstadoEndFornecedor)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jtfEstadoEndFornecedor, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jpEmailFornecedor.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "E-mail", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Times New Roman", 1, 12))); // NOI18N

        jtfEmailFornecedor.setFont(new java.awt.Font("Times New Roman", 0, 12)); // NOI18N

        javax.swing.GroupLayout jpEmailFornecedorLayout = new javax.swing.GroupLayout(jpEmailFornecedor);
        jpEmailFornecedor.setLayout(jpEmailFornecedorLayout);
        jpEmailFornecedorLayout.setHorizontalGroup(
            jpEmailFornecedorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jpEmailFornecedorLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jtfEmailFornecedor)
                .addContainerGap())
        );
        jpEmailFornecedorLayout.setVerticalGroup(
            jpEmailFornecedorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jtfEmailFornecedor, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        jpTelefoneFornecedor.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Telefone", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Times New Roman", 1, 12))); // NOI18N

        jtfTelefoneFornecedor.setFont(new java.awt.Font("Times New Roman", 0, 12)); // NOI18N

        javax.swing.GroupLayout jpTelefoneFornecedorLayout = new javax.swing.GroupLayout(jpTelefoneFornecedor);
        jpTelefoneFornecedor.setLayout(jpTelefoneFornecedorLayout);
        jpTelefoneFornecedorLayout.setHorizontalGroup(
            jpTelefoneFornecedorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jpTelefoneFornecedorLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jtfTelefoneFornecedor, javax.swing.GroupLayout.DEFAULT_SIZE, 261, Short.MAX_VALUE)
                .addContainerGap())
        );
        jpTelefoneFornecedorLayout.setVerticalGroup(
            jpTelefoneFornecedorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jtfTelefoneFornecedor, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        javax.swing.GroupLayout jpContatoFornecedorLayout = new javax.swing.GroupLayout(jpContatoFornecedor);
        jpContatoFornecedor.setLayout(jpContatoFornecedorLayout);
        jpContatoFornecedorLayout.setHorizontalGroup(
            jpContatoFornecedorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jpContatoFornecedorLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jpContatoFornecedorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jpEnderecoFornecedor, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(jpContatoFornecedorLayout.createSequentialGroup()
                        .addComponent(jpEmailFornecedor, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jpTelefoneFornecedor, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap())
        );
        jpContatoFornecedorLayout.setVerticalGroup(
            jpContatoFornecedorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jpContatoFornecedorLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jpEnderecoFornecedor, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jpContatoFornecedorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jpEmailFornecedor, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jpTelefoneFornecedor, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jbSalvarFornecedor.setFont(new java.awt.Font("Times New Roman", 1, 12)); // NOI18N
        jbSalvarFornecedor.setIcon(new javax.swing.ImageIcon(getClass().getResource("/IMAGENS/1salvar.png"))); // NOI18N
        jbSalvarFornecedor.setText("  Salvar");
        jbSalvarFornecedor.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbSalvarFornecedorActionPerformed(evt);
            }
        });

        jbCancelarFornecedor1.setFont(new java.awt.Font("Times New Roman", 1, 12)); // NOI18N
        jbCancelarFornecedor1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/IMAGENS/1excluir.png"))); // NOI18N
        jbCancelarFornecedor1.setText("  Cancelar");
        jbCancelarFornecedor1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbCancelarFornecedor1ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jpCadatroFornecedorLayout = new javax.swing.GroupLayout(jpCadatroFornecedor);
        jpCadatroFornecedor.setLayout(jpCadatroFornecedorLayout);
        jpCadatroFornecedorLayout.setHorizontalGroup(
            jpCadatroFornecedorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jpCadatroFornecedorLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jpCadatroFornecedorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jpCadatroFornecedorLayout.createSequentialGroup()
                        .addComponent(jbSalvarFornecedor, javax.swing.GroupLayout.PREFERRED_SIZE, 123, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jbCancelarFornecedor1))
                    .addGroup(jpCadatroFornecedorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                        .addComponent(jpContatoFornecedor, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(jpCadatroFornecedorLayout.createSequentialGroup()
                            .addComponent(jlCodigoFornecedor)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                            .addComponent(jlCodigoNumFornecedor))
                        .addComponent(jpDadosFornecedor, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                .addGap(0, 20, Short.MAX_VALUE))
        );
        jpCadatroFornecedorLayout.setVerticalGroup(
            jpCadatroFornecedorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jpCadatroFornecedorLayout.createSequentialGroup()
                .addGap(7, 7, 7)
                .addGroup(jpCadatroFornecedorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jlCodigoFornecedor)
                    .addComponent(jlCodigoNumFornecedor))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jpDadosFornecedor, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jpContatoFornecedor, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jpCadatroFornecedorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jbCancelarFornecedor1)
                    .addComponent(jbSalvarFornecedor))
                .addContainerGap(16, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jpCadatroFornecedor, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jpCadatroFornecedor, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jbSalvarFornecedorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbSalvarFornecedorActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jbSalvarFornecedorActionPerformed

    private void jbCancelarFornecedor1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbCancelarFornecedor1ActionPerformed
        dispose();
    }//GEN-LAST:event_jbCancelarFornecedor1ActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jbCancelarFornecedor1;
    private javax.swing.JButton jbSalvarFornecedor;
    private javax.swing.JLabel jlBairroEndFornecedor;
    private javax.swing.JLabel jlCepEndFornecedor;
    private javax.swing.JLabel jlCidadeEndFornecedor;
    private javax.swing.JLabel jlCnpjFornecedor;
    private javax.swing.JLabel jlCodigoFornecedor;
    private javax.swing.JLabel jlCodigoNumFornecedor;
    private javax.swing.JLabel jlComplementoEndFornecedor;
    private javax.swing.JLabel jlEstadoEndFornecedor;
    private javax.swing.JLabel jlInscEstadualFornecedor;
    private javax.swing.JLabel jlLogadouroFornecedor;
    private javax.swing.JLabel jlNumeroEndFornecedor;
    private javax.swing.JLabel jlRazaoSocialFornecedor;
    private javax.swing.JPanel jpCadatroFornecedor;
    private javax.swing.JPanel jpContatoFornecedor;
    private javax.swing.JPanel jpDadosFornecedor;
    private javax.swing.JPanel jpEmailFornecedor;
    private javax.swing.JPanel jpEnderecoFornecedor;
    private javax.swing.JPanel jpTelefoneFornecedor;
    private javax.swing.JTextField jtfBairroEndFornecedor;
    private javax.swing.JTextField jtfCepEndFornecedor;
    private javax.swing.JTextField jtfCidadeEndFornecedor;
    private javax.swing.JTextField jtfCnpjFornecedor;
    private javax.swing.JTextField jtfComplementoEndFornecedor;
    private javax.swing.JTextField jtfEmailFornecedor;
    private javax.swing.JTextField jtfEstadoEndFornecedor;
    private javax.swing.JTextField jtfInscEstadualFornecedor;
    private javax.swing.JTextField jtfLogadouroFornecedor;
    private javax.swing.JTextField jtfNumeroEndFornecedor;
    private javax.swing.JTextField jtfRazaoSocialFornecedor;
    private javax.swing.JTextField jtfTelefoneFornecedor;
    // End of variables declaration//GEN-END:variables
}
