/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package VIEW;

/**
 *
 * @author Roberto Junior Akira
 */
public class JIFNovoCadastroClienteFisico extends javax.swing.JInternalFrame {

    /**
     * Creates new form JIFCadastroClientes
     */
    public JIFNovoCadastroClienteFisico() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        jpCadatroClienteFisico4 = new javax.swing.JPanel();
        jlCodigoClienteFisico4 = new javax.swing.JLabel();
        jlCodigoNumClienteFisico4 = new javax.swing.JLabel();
        jpDadosPessoaisClienteFisico4 = new javax.swing.JPanel();
        jlNomeClienteFisico4 = new javax.swing.JLabel();
        jtfnomeClienteFisico4 = new javax.swing.JTextField();
        jlSexoClienteFisico4 = new javax.swing.JLabel();
        jcbSexoClienteFisico4 = new javax.swing.JComboBox<>();
        jlCpfClienteFisico4 = new javax.swing.JLabel();
        jtfCpfClienteFisico4 = new javax.swing.JTextField();
        jlRgClienteFisico4 = new javax.swing.JLabel();
        jtfRgClienteFisico4 = new javax.swing.JTextField();
        jlDataNascimentoClienteFisico4 = new javax.swing.JLabel();
        jtfDataNascimentoClienteFisico4 = new javax.swing.JTextField();
        jpContatoClienteFisico = new javax.swing.JPanel();
        jpEnderecoClienteFisico = new javax.swing.JPanel();
        jlLogadouroClienteFisico = new javax.swing.JLabel();
        jtfLogadouroClienteFisico = new javax.swing.JTextField();
        jlNumeroEndClienteFisico = new javax.swing.JLabel();
        jtfNumeroEndClienteFisico = new javax.swing.JTextField();
        jlComplementoEndClienteFisico = new javax.swing.JLabel();
        jtfComplementoEndClienteFisico = new javax.swing.JTextField();
        jlBairroEndClienteFisico = new javax.swing.JLabel();
        jtfBairroEndClienteFisico = new javax.swing.JTextField();
        jlCepEndClienteFisico = new javax.swing.JLabel();
        jtfCepEndClienteFisico = new javax.swing.JTextField();
        jlCidadeEndClienteFisico = new javax.swing.JLabel();
        jtfCidadeEndClienteFisico = new javax.swing.JTextField();
        jlEstadoEndClienteFisico = new javax.swing.JLabel();
        jtfEstadoEndClienteFisico = new javax.swing.JTextField();
        jpEmailClienteFisico = new javax.swing.JPanel();
        jtfEmailClienteFisico = new javax.swing.JTextField();
        jpTelefoneClienteFisico = new javax.swing.JPanel();
        jtfTelefoneClienteFisico = new javax.swing.JTextField();
        jbSalvarClienteFisico = new javax.swing.JButton();
        jbCancelarClienteFisico1 = new javax.swing.JButton();

        setClosable(true);
        setIconifiable(true);

        jpCadatroClienteFisico4.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Cliente Físico", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Times New Roman", 1, 12))); // NOI18N

        jlCodigoClienteFisico4.setFont(new java.awt.Font("Times New Roman", 1, 12)); // NOI18N
        jlCodigoClienteFisico4.setText("Código");

        jlCodigoNumClienteFisico4.setFont(new java.awt.Font("Times New Roman", 1, 12)); // NOI18N
        jlCodigoNumClienteFisico4.setText("0");

        jpDadosPessoaisClienteFisico4.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Dados Pessoais", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Times New Roman", 1, 12))); // NOI18N

        jlNomeClienteFisico4.setFont(new java.awt.Font("Times New Roman", 1, 12)); // NOI18N
        jlNomeClienteFisico4.setText("Nome completo");

        jtfnomeClienteFisico4.setFont(new java.awt.Font("Times New Roman", 0, 12)); // NOI18N

        jlSexoClienteFisico4.setFont(new java.awt.Font("Times New Roman", 1, 12)); // NOI18N
        jlSexoClienteFisico4.setText("Sexo");

        jcbSexoClienteFisico4.setFont(new java.awt.Font("Times New Roman", 0, 12)); // NOI18N
        jcbSexoClienteFisico4.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Selecione", "Masculino", "Feminino", "Outros" }));

        jlCpfClienteFisico4.setFont(new java.awt.Font("Times New Roman", 1, 12)); // NOI18N
        jlCpfClienteFisico4.setText("CPF");

        jtfCpfClienteFisico4.setFont(new java.awt.Font("Times New Roman", 0, 12)); // NOI18N

        jlRgClienteFisico4.setFont(new java.awt.Font("Times New Roman", 1, 12)); // NOI18N
        jlRgClienteFisico4.setText("RG");

        jtfRgClienteFisico4.setFont(new java.awt.Font("Times New Roman", 0, 12)); // NOI18N

        jlDataNascimentoClienteFisico4.setFont(new java.awt.Font("Times New Roman", 1, 12)); // NOI18N
        jlDataNascimentoClienteFisico4.setText("Data Nascimento");

        jtfDataNascimentoClienteFisico4.setFont(new java.awt.Font("Times New Roman", 0, 12)); // NOI18N

        javax.swing.GroupLayout jpDadosPessoaisClienteFisico4Layout = new javax.swing.GroupLayout(jpDadosPessoaisClienteFisico4);
        jpDadosPessoaisClienteFisico4.setLayout(jpDadosPessoaisClienteFisico4Layout);
        jpDadosPessoaisClienteFisico4Layout.setHorizontalGroup(
            jpDadosPessoaisClienteFisico4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jpDadosPessoaisClienteFisico4Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jpDadosPessoaisClienteFisico4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(jpDadosPessoaisClienteFisico4Layout.createSequentialGroup()
                        .addGroup(jpDadosPessoaisClienteFisico4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jlCpfClienteFisico4)
                            .addComponent(jtfCpfClienteFisico4, javax.swing.GroupLayout.PREFERRED_SIZE, 201, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGroup(jpDadosPessoaisClienteFisico4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jpDadosPessoaisClienteFisico4Layout.createSequentialGroup()
                                .addGap(22, 22, 22)
                                .addComponent(jlRgClienteFisico4))
                            .addGroup(jpDadosPessoaisClienteFisico4Layout.createSequentialGroup()
                                .addGap(18, 18, 18)
                                .addComponent(jtfRgClienteFisico4, javax.swing.GroupLayout.PREFERRED_SIZE, 228, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(18, 18, 18)
                        .addGroup(jpDadosPessoaisClienteFisico4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jlDataNascimentoClienteFisico4)
                            .addComponent(jtfDataNascimentoClienteFisico4, javax.swing.GroupLayout.PREFERRED_SIZE, 125, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(jpDadosPessoaisClienteFisico4Layout.createSequentialGroup()
                        .addGroup(jpDadosPessoaisClienteFisico4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jlNomeClienteFisico4)
                            .addComponent(jtfnomeClienteFisico4, javax.swing.GroupLayout.PREFERRED_SIZE, 478, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(jpDadosPessoaisClienteFisico4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jlSexoClienteFisico4)
                            .addComponent(jcbSexoClienteFisico4, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jpDadosPessoaisClienteFisico4Layout.setVerticalGroup(
            jpDadosPessoaisClienteFisico4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jpDadosPessoaisClienteFisico4Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jpDadosPessoaisClienteFisico4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jpDadosPessoaisClienteFisico4Layout.createSequentialGroup()
                        .addGroup(jpDadosPessoaisClienteFisico4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(jpDadosPessoaisClienteFisico4Layout.createSequentialGroup()
                                .addComponent(jlSexoClienteFisico4)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jcbSexoClienteFisico4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jpDadosPessoaisClienteFisico4Layout.createSequentialGroup()
                                .addComponent(jlNomeClienteFisico4)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jtfnomeClienteFisico4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(jpDadosPessoaisClienteFisico4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jlRgClienteFisico4)
                            .addGroup(jpDadosPessoaisClienteFisico4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                .addGroup(jpDadosPessoaisClienteFisico4Layout.createSequentialGroup()
                                    .addComponent(jlCpfClienteFisico4)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                    .addComponent(jtfCpfClienteFisico4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGroup(jpDadosPessoaisClienteFisico4Layout.createSequentialGroup()
                                    .addComponent(jlDataNascimentoClienteFisico4)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                    .addComponent(jtfDataNascimentoClienteFisico4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                    .addComponent(jtfRgClienteFisico4, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jpContatoClienteFisico.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Contato", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Times New Roman", 1, 12))); // NOI18N

        jpEnderecoClienteFisico.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Endereço", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Times New Roman", 1, 12))); // NOI18N

        jlLogadouroClienteFisico.setFont(new java.awt.Font("Times New Roman", 1, 12)); // NOI18N
        jlLogadouroClienteFisico.setText("Logadouro");

        jtfLogadouroClienteFisico.setFont(new java.awt.Font("Times New Roman", 0, 12)); // NOI18N

        jlNumeroEndClienteFisico.setFont(new java.awt.Font("Times New Roman", 1, 12)); // NOI18N
        jlNumeroEndClienteFisico.setText("Número");

        jtfNumeroEndClienteFisico.setFont(new java.awt.Font("Times New Roman", 0, 12)); // NOI18N

        jlComplementoEndClienteFisico.setFont(new java.awt.Font("Times New Roman", 1, 12)); // NOI18N
        jlComplementoEndClienteFisico.setText("Complemento");

        jtfComplementoEndClienteFisico.setFont(new java.awt.Font("Times New Roman", 0, 12)); // NOI18N

        jlBairroEndClienteFisico.setFont(new java.awt.Font("Times New Roman", 1, 12)); // NOI18N
        jlBairroEndClienteFisico.setText("Bairro");

        jtfBairroEndClienteFisico.setFont(new java.awt.Font("Times New Roman", 0, 12)); // NOI18N

        jlCepEndClienteFisico.setFont(new java.awt.Font("Times New Roman", 1, 12)); // NOI18N
        jlCepEndClienteFisico.setText("CEP");

        jtfCepEndClienteFisico.setFont(new java.awt.Font("Times New Roman", 0, 12)); // NOI18N

        jlCidadeEndClienteFisico.setFont(new java.awt.Font("Times New Roman", 1, 12)); // NOI18N
        jlCidadeEndClienteFisico.setText("Cidade");

        jtfCidadeEndClienteFisico.setFont(new java.awt.Font("Times New Roman", 0, 12)); // NOI18N

        jlEstadoEndClienteFisico.setFont(new java.awt.Font("Times New Roman", 1, 12)); // NOI18N
        jlEstadoEndClienteFisico.setText("Estado");

        jtfEstadoEndClienteFisico.setFont(new java.awt.Font("Times New Roman", 0, 12)); // NOI18N

        javax.swing.GroupLayout jpEnderecoClienteFisicoLayout = new javax.swing.GroupLayout(jpEnderecoClienteFisico);
        jpEnderecoClienteFisico.setLayout(jpEnderecoClienteFisicoLayout);
        jpEnderecoClienteFisicoLayout.setHorizontalGroup(
            jpEnderecoClienteFisicoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jpEnderecoClienteFisicoLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jpEnderecoClienteFisicoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jpEnderecoClienteFisicoLayout.createSequentialGroup()
                        .addGroup(jpEnderecoClienteFisicoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jlBairroEndClienteFisico, javax.swing.GroupLayout.PREFERRED_SIZE, 79, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jtfBairroEndClienteFisico, javax.swing.GroupLayout.PREFERRED_SIZE, 166, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(jpEnderecoClienteFisicoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jlCepEndClienteFisico, javax.swing.GroupLayout.PREFERRED_SIZE, 79, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jtfCepEndClienteFisico, javax.swing.GroupLayout.PREFERRED_SIZE, 128, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(jpEnderecoClienteFisicoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jlCidadeEndClienteFisico, javax.swing.GroupLayout.PREFERRED_SIZE, 79, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jtfCidadeEndClienteFisico, javax.swing.GroupLayout.PREFERRED_SIZE, 136, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(jpEnderecoClienteFisicoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jlEstadoEndClienteFisico, javax.swing.GroupLayout.PREFERRED_SIZE, 79, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jtfEstadoEndClienteFisico, javax.swing.GroupLayout.PREFERRED_SIZE, 107, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(jpEnderecoClienteFisicoLayout.createSequentialGroup()
                        .addGroup(jpEnderecoClienteFisicoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jpEnderecoClienteFisicoLayout.createSequentialGroup()
                                .addComponent(jlLogadouroClienteFisico, javax.swing.GroupLayout.PREFERRED_SIZE, 79, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(0, 0, Short.MAX_VALUE))
                            .addComponent(jtfLogadouroClienteFisico))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(jpEnderecoClienteFisicoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jlNumeroEndClienteFisico, javax.swing.GroupLayout.PREFERRED_SIZE, 79, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jtfNumeroEndClienteFisico, javax.swing.GroupLayout.PREFERRED_SIZE, 107, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(jpEnderecoClienteFisicoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jlComplementoEndClienteFisico, javax.swing.GroupLayout.PREFERRED_SIZE, 79, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jtfComplementoEndClienteFisico, javax.swing.GroupLayout.PREFERRED_SIZE, 107, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addContainerGap())
        );
        jpEnderecoClienteFisicoLayout.setVerticalGroup(
            jpEnderecoClienteFisicoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jpEnderecoClienteFisicoLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jpEnderecoClienteFisicoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jpEnderecoClienteFisicoLayout.createSequentialGroup()
                        .addComponent(jlLogadouroClienteFisico)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jtfLogadouroClienteFisico, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jpEnderecoClienteFisicoLayout.createSequentialGroup()
                        .addComponent(jlNumeroEndClienteFisico)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jtfNumeroEndClienteFisico, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jpEnderecoClienteFisicoLayout.createSequentialGroup()
                        .addComponent(jlComplementoEndClienteFisico)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jtfComplementoEndClienteFisico, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jpEnderecoClienteFisicoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jpEnderecoClienteFisicoLayout.createSequentialGroup()
                        .addComponent(jlBairroEndClienteFisico)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jtfBairroEndClienteFisico, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jpEnderecoClienteFisicoLayout.createSequentialGroup()
                        .addComponent(jlCepEndClienteFisico)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jtfCepEndClienteFisico, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jpEnderecoClienteFisicoLayout.createSequentialGroup()
                        .addComponent(jlCidadeEndClienteFisico)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jtfCidadeEndClienteFisico, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jpEnderecoClienteFisicoLayout.createSequentialGroup()
                        .addComponent(jlEstadoEndClienteFisico)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jtfEstadoEndClienteFisico, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jpEmailClienteFisico.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "E-mail", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Times New Roman", 1, 12))); // NOI18N

        jtfEmailClienteFisico.setFont(new java.awt.Font("Times New Roman", 0, 12)); // NOI18N

        javax.swing.GroupLayout jpEmailClienteFisicoLayout = new javax.swing.GroupLayout(jpEmailClienteFisico);
        jpEmailClienteFisico.setLayout(jpEmailClienteFisicoLayout);
        jpEmailClienteFisicoLayout.setHorizontalGroup(
            jpEmailClienteFisicoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jpEmailClienteFisicoLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jtfEmailClienteFisico)
                .addContainerGap())
        );
        jpEmailClienteFisicoLayout.setVerticalGroup(
            jpEmailClienteFisicoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jtfEmailClienteFisico, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        jpTelefoneClienteFisico.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Telefone", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Times New Roman", 1, 12))); // NOI18N

        jtfTelefoneClienteFisico.setFont(new java.awt.Font("Times New Roman", 0, 12)); // NOI18N

        javax.swing.GroupLayout jpTelefoneClienteFisicoLayout = new javax.swing.GroupLayout(jpTelefoneClienteFisico);
        jpTelefoneClienteFisico.setLayout(jpTelefoneClienteFisicoLayout);
        jpTelefoneClienteFisicoLayout.setHorizontalGroup(
            jpTelefoneClienteFisicoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jpTelefoneClienteFisicoLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jtfTelefoneClienteFisico, javax.swing.GroupLayout.DEFAULT_SIZE, 261, Short.MAX_VALUE)
                .addContainerGap())
        );
        jpTelefoneClienteFisicoLayout.setVerticalGroup(
            jpTelefoneClienteFisicoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jtfTelefoneClienteFisico, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        javax.swing.GroupLayout jpContatoClienteFisicoLayout = new javax.swing.GroupLayout(jpContatoClienteFisico);
        jpContatoClienteFisico.setLayout(jpContatoClienteFisicoLayout);
        jpContatoClienteFisicoLayout.setHorizontalGroup(
            jpContatoClienteFisicoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jpContatoClienteFisicoLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jpContatoClienteFisicoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jpEnderecoClienteFisico, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(jpContatoClienteFisicoLayout.createSequentialGroup()
                        .addComponent(jpEmailClienteFisico, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jpTelefoneClienteFisico, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap())
        );
        jpContatoClienteFisicoLayout.setVerticalGroup(
            jpContatoClienteFisicoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jpContatoClienteFisicoLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jpEnderecoClienteFisico, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jpContatoClienteFisicoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jpEmailClienteFisico, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jpTelefoneClienteFisico, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jbSalvarClienteFisico.setFont(new java.awt.Font("Times New Roman", 1, 12)); // NOI18N
        jbSalvarClienteFisico.setIcon(new javax.swing.ImageIcon(getClass().getResource("/IMAGENS/1salvar.png"))); // NOI18N
        jbSalvarClienteFisico.setText("  Salvar");
        jbSalvarClienteFisico.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbSalvarClienteFisicoActionPerformed(evt);
            }
        });

        jbCancelarClienteFisico1.setFont(new java.awt.Font("Times New Roman", 1, 12)); // NOI18N
        jbCancelarClienteFisico1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/IMAGENS/1excluir.png"))); // NOI18N
        jbCancelarClienteFisico1.setText("  Cancelar");
        jbCancelarClienteFisico1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbCancelarClienteFisico1ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jpCadatroClienteFisico4Layout = new javax.swing.GroupLayout(jpCadatroClienteFisico4);
        jpCadatroClienteFisico4.setLayout(jpCadatroClienteFisico4Layout);
        jpCadatroClienteFisico4Layout.setHorizontalGroup(
            jpCadatroClienteFisico4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jpCadatroClienteFisico4Layout.createSequentialGroup()
                .addGroup(jpCadatroClienteFisico4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jpCadatroClienteFisico4Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jlCodigoClienteFisico4)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jlCodigoNumClienteFisico4))
                    .addGroup(jpCadatroClienteFisico4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                        .addGroup(jpCadatroClienteFisico4Layout.createSequentialGroup()
                            .addComponent(jbSalvarClienteFisico, javax.swing.GroupLayout.PREFERRED_SIZE, 123, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                            .addComponent(jbCancelarClienteFisico1))
                        .addGroup(jpCadatroClienteFisico4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addComponent(jpContatoClienteFisico, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jpDadosPessoaisClienteFisico4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
                .addGap(0, 29, Short.MAX_VALUE))
        );
        jpCadatroClienteFisico4Layout.setVerticalGroup(
            jpCadatroClienteFisico4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jpCadatroClienteFisico4Layout.createSequentialGroup()
                .addGap(7, 7, 7)
                .addGroup(jpCadatroClienteFisico4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jlCodigoClienteFisico4)
                    .addComponent(jlCodigoNumClienteFisico4))
                .addGap(18, 18, 18)
                .addComponent(jpDadosPessoaisClienteFisico4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jpContatoClienteFisico, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jpCadatroClienteFisico4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jbSalvarClienteFisico)
                    .addComponent(jbCancelarClienteFisico1))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jScrollPane1.setViewportView(jpCadatroClienteFisico4);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane1)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jbSalvarClienteFisicoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbSalvarClienteFisicoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jbSalvarClienteFisicoActionPerformed

    private void jbCancelarClienteFisico1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbCancelarClienteFisico1ActionPerformed
        dispose();
    }//GEN-LAST:event_jbCancelarClienteFisico1ActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JButton jbCancelarClienteFisico1;
    private javax.swing.JButton jbSalvarClienteFisico;
    private javax.swing.JComboBox<String> jcbSexoClienteFisico4;
    private javax.swing.JLabel jlBairroEndClienteFisico;
    private javax.swing.JLabel jlCepEndClienteFisico;
    private javax.swing.JLabel jlCidadeEndClienteFisico;
    private javax.swing.JLabel jlCodigoClienteFisico4;
    private javax.swing.JLabel jlCodigoNumClienteFisico4;
    private javax.swing.JLabel jlComplementoEndClienteFisico;
    private javax.swing.JLabel jlCpfClienteFisico4;
    private javax.swing.JLabel jlDataNascimentoClienteFisico4;
    private javax.swing.JLabel jlEstadoEndClienteFisico;
    private javax.swing.JLabel jlLogadouroClienteFisico;
    private javax.swing.JLabel jlNomeClienteFisico4;
    private javax.swing.JLabel jlNumeroEndClienteFisico;
    private javax.swing.JLabel jlRgClienteFisico4;
    private javax.swing.JLabel jlSexoClienteFisico4;
    private javax.swing.JPanel jpCadatroClienteFisico4;
    private javax.swing.JPanel jpContatoClienteFisico;
    private javax.swing.JPanel jpDadosPessoaisClienteFisico4;
    private javax.swing.JPanel jpEmailClienteFisico;
    private javax.swing.JPanel jpEnderecoClienteFisico;
    private javax.swing.JPanel jpTelefoneClienteFisico;
    private javax.swing.JTextField jtfBairroEndClienteFisico;
    private javax.swing.JTextField jtfCepEndClienteFisico;
    private javax.swing.JTextField jtfCidadeEndClienteFisico;
    private javax.swing.JTextField jtfComplementoEndClienteFisico;
    private javax.swing.JTextField jtfCpfClienteFisico4;
    private javax.swing.JTextField jtfDataNascimentoClienteFisico4;
    private javax.swing.JTextField jtfEmailClienteFisico;
    private javax.swing.JTextField jtfEstadoEndClienteFisico;
    private javax.swing.JTextField jtfLogadouroClienteFisico;
    private javax.swing.JTextField jtfNumeroEndClienteFisico;
    private javax.swing.JTextField jtfRgClienteFisico4;
    private javax.swing.JTextField jtfTelefoneClienteFisico;
    private javax.swing.JTextField jtfnomeClienteFisico4;
    // End of variables declaration//GEN-END:variables
}
