/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package VIEW;

/**
 *
 * @author Roberto Junior Akira
 */
public class JIFSobre extends javax.swing.JInternalFrame {

    /**
     * Creates new form JIFSobre
     */
    public JIFSobre() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jpSobre = new javax.swing.JPanel();
        jlCarrinho = new javax.swing.JLabel();
        jlRiverland = new javax.swing.JLabel();
        jlSupermercado = new javax.swing.JLabel();
        jpVersao = new javax.swing.JPanel();
        jlSistema = new javax.swing.JLabel();
        jpVersao1 = new javax.swing.JPanel();
        jlSistema1 = new javax.swing.JLabel();

        setClosable(true);
        setTitle("Sobre");

        jpSobre.setBackground(new java.awt.Color(0, 102, 153));
        jpSobre.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 0), 1, true));

        jlCarrinho.setIcon(new javax.swing.ImageIcon(getClass().getResource("/IMAGENS/carrinho48.png"))); // NOI18N

        jlRiverland.setFont(new java.awt.Font("Impact", 0, 18)); // NOI18N
        jlRiverland.setText("RIVERLAND");

        jlSupermercado.setFont(new java.awt.Font("Impact", 0, 18)); // NOI18N
        jlSupermercado.setText("SUPERMERCADO");

        javax.swing.GroupLayout jpSobreLayout = new javax.swing.GroupLayout(jpSobre);
        jpSobre.setLayout(jpSobreLayout);
        jpSobreLayout.setHorizontalGroup(
            jpSobreLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jpSobreLayout.createSequentialGroup()
                .addGap(103, 103, 103)
                .addComponent(jlCarrinho)
                .addGap(18, 18, 18)
                .addGroup(jpSobreLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jlSupermercado)
                    .addGroup(jpSobreLayout.createSequentialGroup()
                        .addGap(10, 10, 10)
                        .addComponent(jlRiverland)))
                .addContainerGap(102, Short.MAX_VALUE))
        );
        jpSobreLayout.setVerticalGroup(
            jpSobreLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jpSobreLayout.createSequentialGroup()
                .addGap(72, 72, 72)
                .addGroup(jpSobreLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jlCarrinho)
                    .addGroup(jpSobreLayout.createSequentialGroup()
                        .addComponent(jlSupermercado)
                        .addGap(2, 2, 2)
                        .addComponent(jlRiverland)))
                .addContainerGap(77, Short.MAX_VALUE))
        );

        jpVersao.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Creation", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Times New Roman", 1, 12))); // NOI18N

        jlSistema.setFont(new java.awt.Font("Times New Roman", 2, 14)); // NOI18N
        jlSistema.setText("Roberto Akira Ozaki Junior");

        javax.swing.GroupLayout jpVersaoLayout = new javax.swing.GroupLayout(jpVersao);
        jpVersao.setLayout(jpVersaoLayout);
        jpVersaoLayout.setHorizontalGroup(
            jpVersaoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jpVersaoLayout.createSequentialGroup()
                .addGap(115, 115, 115)
                .addComponent(jlSistema)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jpVersaoLayout.setVerticalGroup(
            jpVersaoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jpVersaoLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jlSistema)
                .addContainerGap())
        );

        jpVersao1.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Version", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Times New Roman", 1, 12))); // NOI18N

        jlSistema1.setFont(new java.awt.Font("Times New Roman", 2, 14)); // NOI18N
        jlSistema1.setText("Sistema: 1111.11.11");

        javax.swing.GroupLayout jpVersao1Layout = new javax.swing.GroupLayout(jpVersao1);
        jpVersao1.setLayout(jpVersao1Layout);
        jpVersao1Layout.setHorizontalGroup(
            jpVersao1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jpVersao1Layout.createSequentialGroup()
                .addGap(130, 130, 130)
                .addComponent(jlSistema1)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jpVersao1Layout.setVerticalGroup(
            jpVersao1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jpVersao1Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jlSistema1)
                .addContainerGap())
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addComponent(jpVersao1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jpSobre, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jpVersao, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(0, 10, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jpSobre, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jpVersao1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jpVersao, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(16, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jlCarrinho;
    private javax.swing.JLabel jlRiverland;
    private javax.swing.JLabel jlSistema;
    private javax.swing.JLabel jlSistema1;
    private javax.swing.JLabel jlSupermercado;
    private javax.swing.JPanel jpSobre;
    private javax.swing.JPanel jpVersao;
    private javax.swing.JPanel jpVersao1;
    // End of variables declaration//GEN-END:variables
}
