/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package VIEW;

/**
 *
 * @author Roberto Junior Akira
 */
public class JIFVendas extends javax.swing.JInternalFrame {

    /**
     * Creates new form JIFVendas1
     */
    public JIFVendas() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jpVendaJuridico = new javax.swing.JPanel();
        jpCliente = new javax.swing.JPanel();
        jlCnpjCpfCliente = new javax.swing.JLabel();
        jtfCnpjCpfCliente = new javax.swing.JTextField();
        jlRazaoSocialNomeCliente = new javax.swing.JLabel();
        jtfRazaoSocialNomeCliente = new javax.swing.JTextField();
        jpCompra = new javax.swing.JPanel();
        jScrollPane16 = new javax.swing.JScrollPane();
        jtVendaProd = new javax.swing.JTable();
        jbImprimirVenda = new javax.swing.JButton();
        jlIdVenda = new javax.swing.JLabel();
        jlNumIdVenda = new javax.swing.JLabel();
        jpValorTotalVenda = new javax.swing.JPanel();
        jlValorTotalVenda2 = new javax.swing.JLabel();
        jtfValorTotalVenda = new javax.swing.JTextField();
        jlDataVenda = new javax.swing.JLabel();
        jtfDataVenda = new javax.swing.JTextField();
        jpVendas = new javax.swing.JPanel();
        jpDadosVendas = new javax.swing.JPanel();
        jtfNumVenda = new javax.swing.JTextField();
        jScrollPane2 = new javax.swing.JScrollPane();
        jtVendas = new javax.swing.JTable();

        setClosable(true);
        setIconifiable(true);

        jpVendaJuridico.setBackground(new java.awt.Color(0, 102, 153));
        jpVendaJuridico.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "VENDA", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Times New Roman", 1, 12))); // NOI18N

        jpCliente.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Cliente Juridico", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Times New Roman", 1, 12))); // NOI18N

        jlCnpjCpfCliente.setFont(new java.awt.Font("Times New Roman", 1, 12)); // NOI18N
        jlCnpjCpfCliente.setText("CNPJ / CPF");

        jtfCnpjCpfCliente.setFont(new java.awt.Font("Times New Roman", 0, 12)); // NOI18N
        jtfCnpjCpfCliente.setEnabled(false);

        jlRazaoSocialNomeCliente.setFont(new java.awt.Font("Times New Roman", 1, 12)); // NOI18N
        jlRazaoSocialNomeCliente.setText("Razão Social / Nome");

        jtfRazaoSocialNomeCliente.setFont(new java.awt.Font("Times New Roman", 0, 12)); // NOI18N
        jtfRazaoSocialNomeCliente.setEnabled(false);

        javax.swing.GroupLayout jpClienteLayout = new javax.swing.GroupLayout(jpCliente);
        jpCliente.setLayout(jpClienteLayout);
        jpClienteLayout.setHorizontalGroup(
            jpClienteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jpClienteLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jpClienteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jlCnpjCpfCliente)
                    .addComponent(jtfCnpjCpfCliente, javax.swing.GroupLayout.PREFERRED_SIZE, 201, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jpClienteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jpClienteLayout.createSequentialGroup()
                        .addComponent(jlRazaoSocialNomeCliente)
                        .addGap(0, 302, Short.MAX_VALUE))
                    .addComponent(jtfRazaoSocialNomeCliente))
                .addContainerGap())
        );
        jpClienteLayout.setVerticalGroup(
            jpClienteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jpClienteLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jpClienteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jpClienteLayout.createSequentialGroup()
                        .addComponent(jlRazaoSocialNomeCliente)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jtfRazaoSocialNomeCliente, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jpClienteLayout.createSequentialGroup()
                        .addComponent(jlCnpjCpfCliente)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jtfCnpjCpfCliente, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jpCompra.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Venda", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Times New Roman", 1, 12))); // NOI18N

        jtVendaProd.setFont(new java.awt.Font("Times New Roman", 0, 12)); // NOI18N
        jtVendaProd.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null}
            },
            new String [] {
                "CÓDIGO", "DESCRIÇÃO", "UN", "QTD", "VALOR UNIT", "VALOR TOTAL"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.Object.class
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }
        });
        jtVendaProd.setEnabled(false);
        jScrollPane16.setViewportView(jtVendaProd);

        jbImprimirVenda.setFont(new java.awt.Font("Times New Roman", 1, 12)); // NOI18N
        jbImprimirVenda.setIcon(new javax.swing.ImageIcon(getClass().getResource("/IMAGENS/imprimir.png"))); // NOI18N
        jbImprimirVenda.setText("  Imprimir");

        jlIdVenda.setFont(new java.awt.Font("Times New Roman", 1, 12)); // NOI18N
        jlIdVenda.setText("ID:");

        jlNumIdVenda.setFont(new java.awt.Font("Times New Roman", 1, 12)); // NOI18N
        jlNumIdVenda.setText("0");

        jpValorTotalVenda.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Valor Total da Venda", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Times New Roman", 1, 12))); // NOI18N

        jlValorTotalVenda2.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        jlValorTotalVenda2.setText("R$ ");

        jtfValorTotalVenda.setFont(new java.awt.Font("Times New Roman", 0, 12)); // NOI18N
        jtfValorTotalVenda.setEnabled(false);
        jtfValorTotalVenda.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jtfValorTotalVendaActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jpValorTotalVendaLayout = new javax.swing.GroupLayout(jpValorTotalVenda);
        jpValorTotalVenda.setLayout(jpValorTotalVendaLayout);
        jpValorTotalVendaLayout.setHorizontalGroup(
            jpValorTotalVendaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jpValorTotalVendaLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jlValorTotalVenda2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jtfValorTotalVenda)
                .addContainerGap())
        );
        jpValorTotalVendaLayout.setVerticalGroup(
            jpValorTotalVendaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jpValorTotalVendaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                .addComponent(jlValorTotalVenda2, javax.swing.GroupLayout.DEFAULT_SIZE, 27, Short.MAX_VALUE)
                .addComponent(jtfValorTotalVenda, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        jlDataVenda.setFont(new java.awt.Font("Times New Roman", 1, 12)); // NOI18N
        jlDataVenda.setText("Data:");

        jtfDataVenda.setFont(new java.awt.Font("Times New Roman", 0, 12)); // NOI18N
        jtfDataVenda.setEnabled(false);

        javax.swing.GroupLayout jpCompraLayout = new javax.swing.GroupLayout(jpCompra);
        jpCompra.setLayout(jpCompraLayout);
        jpCompraLayout.setHorizontalGroup(
            jpCompraLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jpCompraLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jpCompraLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jpCompraLayout.createSequentialGroup()
                        .addComponent(jlIdVenda)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jlNumIdVenda)
                        .addGap(27, 27, 27)
                        .addComponent(jlDataVenda)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jtfDataVenda, javax.swing.GroupLayout.PREFERRED_SIZE, 92, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(jpCompraLayout.createSequentialGroup()
                        .addGroup(jpCompraLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jpCompraLayout.createSequentialGroup()
                                .addComponent(jpValorTotalVenda, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addGap(240, 240, 240)
                                .addComponent(jbImprimirVenda)
                                .addGap(10, 10, 10))
                            .addComponent(jScrollPane16, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 629, Short.MAX_VALUE))
                        .addContainerGap())))
        );
        jpCompraLayout.setVerticalGroup(
            jpCompraLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jpCompraLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jpCompraLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jlIdVenda)
                    .addComponent(jlNumIdVenda)
                    .addComponent(jlDataVenda)
                    .addComponent(jtfDataVenda, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(jScrollPane16, javax.swing.GroupLayout.PREFERRED_SIZE, 304, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jpCompraLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jpValorTotalVenda, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jbImprimirVenda))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jpVendas.setFont(new java.awt.Font("Times New Roman", 0, 12)); // NOI18N

        jpDadosVendas.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Pesquisar", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Times New Roman", 1, 12))); // NOI18N

        jtfNumVenda.setFont(new java.awt.Font("Times New Roman", 0, 12)); // NOI18N

        javax.swing.GroupLayout jpDadosVendasLayout = new javax.swing.GroupLayout(jpDadosVendas);
        jpDadosVendas.setLayout(jpDadosVendasLayout);
        jpDadosVendasLayout.setHorizontalGroup(
            jpDadosVendasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jpDadosVendasLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jtfNumVenda)
                .addContainerGap())
        );
        jpDadosVendasLayout.setVerticalGroup(
            jpDadosVendasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jpDadosVendasLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jtfNumVenda, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        jtVendas.setFont(new java.awt.Font("Times New Roman", 0, 12)); // NOI18N
        jtVendas.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null}
            },
            new String [] {
                "Nº VENDA", "DATA", "CNPJ / CPF", "RAZÃO SOCIAL / NOME", "VALOR"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class
            };
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jtVendas.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jtVendasMouseClicked(evt);
            }
        });
        jScrollPane2.setViewportView(jtVendas);

        javax.swing.GroupLayout jpVendasLayout = new javax.swing.GroupLayout(jpVendas);
        jpVendas.setLayout(jpVendasLayout);
        jpVendasLayout.setHorizontalGroup(
            jpVendasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jpVendasLayout.createSequentialGroup()
                .addGroup(jpVendasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jScrollPane2, javax.swing.GroupLayout.DEFAULT_SIZE, 500, Short.MAX_VALUE)
                    .addComponent(jpDadosVendas, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap(12, Short.MAX_VALUE))
        );
        jpVendasLayout.setVerticalGroup(
            jpVendasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jpVendasLayout.createSequentialGroup()
                .addComponent(jpDadosVendas, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 476, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(205, 205, 205))
        );

        javax.swing.GroupLayout jpVendaJuridicoLayout = new javax.swing.GroupLayout(jpVendaJuridico);
        jpVendaJuridico.setLayout(jpVendaJuridicoLayout);
        jpVendaJuridicoLayout.setHorizontalGroup(
            jpVendaJuridicoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jpVendaJuridicoLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jpVendaJuridicoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jpCliente, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jpCompra, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jpVendas, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jpVendaJuridicoLayout.setVerticalGroup(
            jpVendaJuridicoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jpVendaJuridicoLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jpVendaJuridicoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addComponent(jpVendas, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
                    .addGroup(jpVendaJuridicoLayout.createSequentialGroup()
                        .addComponent(jpCliente, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jpCompra, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 1215, Short.MAX_VALUE)
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addGap(0, 0, Short.MAX_VALUE)
                    .addComponent(jpVendaJuridico, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(0, 0, Short.MAX_VALUE)))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 588, Short.MAX_VALUE)
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addGap(0, 0, Short.MAX_VALUE)
                    .addComponent(jpVendaJuridico, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(0, 0, Short.MAX_VALUE)))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jtfValorTotalVendaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jtfValorTotalVendaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jtfValorTotalVendaActionPerformed

    private void jtVendasMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jtVendasMouseClicked
        ;
    }//GEN-LAST:event_jtVendasMouseClicked


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JScrollPane jScrollPane16;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JButton jbImprimirVenda;
    private javax.swing.JLabel jlCnpjCpfCliente;
    private javax.swing.JLabel jlDataVenda;
    private javax.swing.JLabel jlIdVenda;
    private javax.swing.JLabel jlNumIdVenda;
    private javax.swing.JLabel jlRazaoSocialNomeCliente;
    private javax.swing.JLabel jlValorTotalVenda2;
    private javax.swing.JPanel jpCliente;
    private javax.swing.JPanel jpCompra;
    private javax.swing.JPanel jpDadosVendas;
    private javax.swing.JPanel jpValorTotalVenda;
    private javax.swing.JPanel jpVendaJuridico;
    private javax.swing.JPanel jpVendas;
    private javax.swing.JTable jtVendaProd;
    private javax.swing.JTable jtVendas;
    private javax.swing.JTextField jtfCnpjCpfCliente;
    private javax.swing.JTextField jtfDataVenda;
    private javax.swing.JTextField jtfNumVenda;
    private javax.swing.JTextField jtfRazaoSocialNomeCliente;
    private javax.swing.JTextField jtfValorTotalVenda;
    // End of variables declaration//GEN-END:variables
}
